### ISSUE TITLE
basic auth not being enforced for config example

### ISSUE THREAD

**Issue by ryandawsonuk** [elastic/helm-charts#1008]
Am following the [config example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/config) to set basic auth. Have cloned the repo and am following it exactly except for this one change:

```
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-config-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-config-credentials
        key: username
```
Had to change this from the example which says [elastic-credentials](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/config/values.yaml#L9) but it must mean [elastic-config-credentials](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/config/Makefile#L13) as that is the name of the secret. Otherwise I get `Error: secret "elastic-credentials" not found`.

With that change I can install everything.

The example curl of `curl -u elastic:changeme http://localhost:9200/_cat/indices` does indeed give a 200 response. But so does `curl http://localhost:9200/_cat/indices`. It doesn't force me to supply the user and password.

**Comment by jmlrt** [comment]
Hi @ryandawsonuk, thanks for reporting this => #1012 should fix it

**Comment by ryandawsonuk** [comment]
@jmlrt that will get past the secret not found error and I made that change locally. But even with that change I get a 200 from `curl http://localhost:9200/_cat/indices`. If basic auth is being enforced then that should be unauthorized.

**Comment by ryandawsonuk** [comment]
@jmlrt found the problem, the missing ingredient is the xpack.security.enabled flag:
```
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    path.data: /usr/share/elasticsearch/data
```
