### ISSUE TITLE
Statsd module for Metricbeat

### ISSUE THREAD

**Issue by j771** [elastic/helm-charts#1026]
**Chart version:**
7.10.0
**Kubernetes version:**
1.14
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS
**Helm Version:**
3.2.4

I enabled the statsd module with a Metricbeat deployment like so:
```YAML
deployment:
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: statsd
        enabled: true
        host: "localhost"
        port: "8125"
```

This works in making Metricbeat start up the UPD server listening on port 8125.
I did not see an option for a service with this Helm chart so I created a service with selector to the Metricbeat pod on target port 8125.
```YAML
spec:
  ports:
  - name: statsd
    port: 8125
    protocol: UDP
    targetPort: 8125
  selector:
    app: metricbeat-statsd-metrics
    release: metricbeat-statsd
```

I am able to hit the svc with netcat but I am not seeing anything on the Metricbeat side indicating it received the metric (even in debug mode).
```
echo "example:1|c" | nc -w 1 -vcu metricbeat-statsd.metricbeat.svc.cluster.local 8125
  Connection to metricbeat-statsd.metricbeat.svc.cluster.local port 8125 [udp/*] succeeded!
```

Is there something I am missing for setting up Statsd listener for Metricbeat running in k8s?
