### ISSUE TITLE
Cannot enable Filebeat modules through values.yml 

### ISSUE THREAD

**Issue by Izvunzemen** [elastic/helm-charts#1036]
**Chart version:**
7.9.2

**Kubernetes version:**

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS

**Helm Version:**
3.2.0

I try to enable modules from values file, but it didn't work.
values.yaml configuration:
```
...
  filebeatConfig:
    filebeat.yml: |
      filebeat.modules:
      - module: nginx
      - module: mysql
      - module: system
      filebeat.config:
        modules:
          enabled: true
          path: ${path.config}/modules.d/*.yml
...
```

When i do helm install with this config in values file, nothing happen, i tried to list enabled modules inside the container with filebeat modules list, and nginx, mysql, system are still disabled. Configuration is copied in the container's filebeat.yml file tho.  

I am able to enable them only with filebeat modules enable, but this method is not persistent. 

What can be the reason? I tried everything, moving filebeat.modules part after filebeat.config and so on, nothing help.

**Comment by knkarthik** [comment]
@Izvunzemen There's a reported bug https://github.com/elastic/helm-charts/issues/1030. Putting this under the deprecated config works.

**Comment by jmlrt** [comment]
Hi @Izvunzemen,
Thanks for opening this issue.
Unfortunately we currently don't have time to investigate every tickets so please be patient.

**Comment by jmlrt** [comment]
still valid

**Comment by mimartin12** [comment]
Interested in this as well. I am having the exact issue, modules are enabled in the config, but nothing is shown enabled when running `filebeat modules list` inside the container.

**Comment by mimartin12** [comment]
@Izvunzemen @Alvaroca1, 

I was able to get around this by doing the following.

```yaml
deployment:
  filebeatConfig:
      filebeat.yml: |
        filebeat.config:
          modules:
            enabled: true
            path: ${path.config}/module.*.yml
            reload.enabled: true
  
       module.okta.yml: |
              - module: okta
                system:
                  enabled: true
                  var.url: https://yourOktaDomain/api/v1/logs
                  var.api_key: 'test'
   
```
Then `filebeat modules list` output:
```
[root@filebeat-okta-filebeat-6d7d65cf8c-6mfj5 filebeat]# filebeat modules list
Enabled:
module.okta
```

**Comment by olivierboudet** [comment]
/reopen

I am also facing this issue on 7.17.3, I am using the workaround provided by @mimartin12

**Comment by cyanwind23** [comment]
@olivierboudet,

I tried this config then my problem solved (by adding `input.type: container` and changing output to elasticsearch)
```yaml
filebeatConfig:
  filebeat.yml: |
    setup.dashboards.enabled: true
    setup.kibana:
      host: "http://elk-kibana:5601"
      username: ${KIBANA_USERNAME}
      password: ${KIBANA_PASSWORD}
    filebeat.modules:
      - module: nginx
        ingress_controller:
          enabled: true
          var.paths: ["/var/log/containers/ingress-nginx-controller*.log"]
          input.type: container
        access.enabled: false
        error.enabled: false
    output.elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      ssl.certificate_authorities: ["/usr/share/elk/certs/ca.crt"]
      ssl.certificate: "/usr/share/elk/certs/cert.crt"
      ssl.key: "/usr/share/elk/certs/key.pem"
      username: ${KIBANA_USERNAME}
      password: ${KIBANA_PASSWORD}
```

I installed ELK stack v7.17.3 (Filebeat, Logstash, Elasticsearch, Kibana) via Helm and enabled `nginx` module. Although filebeat logs show
```
2023-03-25T06:21:42.171Z	INFO	beater/filebeat.go:118	Enabled modules/filesets: nginx (ingress_controller),  ()
2023-03-25T06:24:00.527Z	INFO	[input]	log/input.go:171	Configured paths: [/var/log/containers/ingress-nginx-controller*.log]	{"input_id": "cf14ddb0-4a84-41ef-a7d2-e2b9bacf0c9d"}
```
but there was no data showed in [Filebeat Nginx] dashboard. 

**Solution:**
- Send events directly to Elasticseach (Ingest node): [more details](https://discuss.elastic.co/t/filebeat-modules-nginx-logstash-elasticsearch-kibana-dont-work-with-autodiscover/169382/5)
- Change module `input.type` to `container` (default `log`)

Hope this help you!
