### ISSUE TITLE
[Bug Report] headless service name missconfigured

### ISSUE THREAD

**Issue by Sherler** [elastic/helm-charts#104]
when I change the value of cluster name to "test", the headless service name is changed correctly, but the  value of env "discovery.zen.ping.unicast.hosts" kept as "elasticsearch-master-headless", and i have to change it manually. here is my value.yaml:  
```yaml
clusterName: test
nodeGroup: master
replicas: 2
minimumMasterNodes: 2
antiAffinity: soft
esMajorVersion: 7
esJavaOpts: "-Xmx8g -Xms8g"

resources:
  requests:
    cpu: 1
    memory: 16Gi
  limits:
    cpu: 1
    memory: 16Gi

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: es-hdd-storage
  resources:
    requests:
      storage: "5Ti"

updateStrategy: RollingUpdate
maxUnavailable: 1
```
