### ISSUE TITLE
Deploy 2 load balancers from the logstash chart

### ISSUE THREAD

**Issue by carl-chenet** [elastic/helm-charts#1041]
**Chart version:**
7.7.0

**Kubernetes version:**
1.8

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS

**Helm Version:**
2.17

I'm using a nlb load balancer for TCP connections, but I would also need another load balancer for the UDP because it is not currently possible to mix TCP and UDP. Is it possible to deploy 2 load balancer from the logstash chart ? I was unsucessful adding another one after the first one, only the last one is deployed.

**Comment by jmlrt** [comment]
Hi @carl-chenet,
Thanks for opening this issue.
Unfortunately we currently don't have time to work on it so please be patient.

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
Hi @carl-chenet,
Looking at https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1608 and https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types, it seems you can now use TCP and UDP in the same LoadBalancer type Service instance starting K8S 1.20. 
Where you able to test it or do you still have a need for a 2nd Service for UDP?

**Comment by framsouza** [comment]
@jmlrt @carl-chenet I managed to test it, I was able to create a service (on k8s 1.20) using TCP and UDP protocol on the same service with the following manifest:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app-np-service
spec:
  type: ClusterIP
  ports:
  - name: tcp-port
    port: 443
    targetPort: 443
    protocol: TCP
  - name: udp-port
    port: 443
    targetPort: 443
    protocol: UDP
  selector:
    app: my-app
```
