### ISSUE TITLE
[filebeat] daemonset.resource doesn't get applied

### ISSUE THREAD

**Issue by Vaproc** [elastic/helm-charts#1049]
**Chart version:**
filebeat 7.10.2
**Kubernetes version:**
v1.18.6
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kops
**Helm Version:**
v3.1.2

`helm upgrade filebeat elastic/filebeat -f values.yaml --debug --dry-run`

<details>
<summary>Output of command (shortened)</summary>

```
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.10.2"
    heritage: "Helm"
    release: "filebeat"
spec:
  selector:
    matchLabels:
      app: "filebeat-filebeat"
      release: "filebeat"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configChecksum: b288ea6ce1b39eea0a4910e33a94027c2defab0d11c982dbcd7c9f27ba694c0
      name: "filebeat-filebeat"
      labels:
        app: "filebeat-filebeat"
        chart: "filebeat-7.10.2"
        heritage: "Helm"
        release: "filebeat"
    spec:
      containers:
      - name: "filebeat"
        image: "docker.elastic.co/beats/filebeat:7.10.2"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
</details>

**Describe the bug:**
`values.yaml` for Filebeat states: 

> resources: {} # deprecated

My values.yaml looks like:
<details>

```
deployment:
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200Mi"
      memory: "200Mi"
```

</details>

But the values are still taken from `.values.resource`.

**Steps to reproduce:**

1. Change resource requests and limits for the daemonset
2. Deploy the chart
3. Compare the deployed daemonset with the values from values.yaml

**Expected behavior:**
Values from daemonset are applied
