### ISSUE TITLE
Make filebeat chart kubernetes-on-windows compatible

### ISSUE THREAD

**Issue by JorritSalverda** [elastic/helm-charts#1050]
**Describe the feature:**

Although filebeat itself works perfectly fine on Windows and Kubernetes on Windows the Helm chart is not configurable enough to use it for both Linux and Windows.

There's 2 notable things that need to be possible:

1. Volume `varlibdockercontainers` needs to have _hostPath_ `/ProgramData/docker/containers` to be able to find the container logs. It can still be mapped to _mountPath_ `/var/lib/docker/containers`, which is actually preferable, because you can then reuse the same config between linux and windows deamonsets.
2. Mounting files with `subPath` is not possible for Windows containers, only directories can be mounted. For that reason filebeat-config and data volumes need to be mounted in different locations, without the `subPath` properties getting used.

**Describe a specific use case for the feature:**

Shipping logs from Kubernetes on Windows nodes.

**Comment by JorritSalverda** [comment]
For using processor `add_kubernetes_metadata` correctly it's useful to set `mountPath: /ProgramData/docker/containers` as well, so preferably it's configurable via the same property.

That works in combination with `filebeat.yaml`:

```yaml
    filebeat.inputs:
    - type: container
      paths:
      - "C:\\ProgramData\\docker\\containers\\*\\*.log"
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
          default_matchers.enabled: false
          matchers:
          - logs_path:
              logs_path: "C:\\ProgramData\\docker\\containers"
```
