### ISSUE TITLE
[apm-server] Example with metricbeat

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1073]
To share with you, how to configure metricbeat to run as a sidecar:

values.yaml

```
  apmConfig:
    apm-server.yml: "....."
    metricbeat.yml: |+
          metricbeat.modules:
          - module: beat
            metricsets:
              - stats
              - state
            period: 10s
            hosts: ["http://localhost:5066"]
            xpack.enabled: true
          output.elasticsearch:
            hosts: 'my_es:9200'
  extraContainers: |+
    - image: docker.elastic.co/beats/metricbeat:7.11.0
      name: metricbeat
      volumeMounts:
      - mountPath: /usr/share/metricbeat/metricbeat.yml
        name: apm-server-config
        readOnly: true
        subPath: metricbeat.yml
```
