### ISSUE TITLE
Support for multiple volumeClaimTemplates and path.data

### ISSUE THREAD

**Issue by gburton1** [elastic/helm-charts#1091]
**Describe the feature:**
It would be useful to be able to specify multiple volumeClaimTemplates, which in turn have multiple mount points that are passed into esConfig as `path.data`. This is a valuable mechanism for scaling horizontally.

**Describe a specific use case for the feature:**
```
    volumeClaimTemplates:
    - metadata:
        name: data1
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: data2
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```
```
        volumeMounts:
        - name: data1
          mountPath: /mnt/path1
        - name: data2
          mountPath: /mnt/path2
```

The usage of those volumes would then be:
```
path.data: [ /mnt/path1, /mnt/path2 ]
```

Reason for supporting it: support the Multiple Data Path (MDP) feature of ES
