### ISSUE TITLE
How to Expose Kibana with TLS on Istio Virtual Service

### ISSUE THREAD

**Issue by rileyhun** [elastic/helm-charts#1149]
Chart version:
7.12.0

Kubernetes version:
1.18.2

Kubernetes provider: GKE

Helm Version:
v3

Describe the bug:
I am able to expose an HTTP-based Kibana service on my Istio Virtual Service no problems. But after applying authentication and TLS following these [instructions](https://github.com/elastic/helm-charts/tree/master/kibana/examples/security), the page doesn't seem to load up. The logs would indicate that Kibana server is starting up

```
{"type":"log","@timestamp":"2021-04-14T04:31:57+00:00","tags":["listening","info"],"pid":6,"message":"Server running at https://0.0.0.0:5601"}
{"type":"log","@timestamp":"2021-04-14T04:31:58+00:00","tags":["info","http","server","Kibana"],"pid":6,"message":"http server running at https://0.0.0.0:5601"}
{"type":"log","@timestamp":"2021-04-14T04:31:58+00:00","tags":["info","plugins","watcher"],"pid":6,"message":"Your basic license does not support watcher. Please upgrade your license."}
{"type":"log","@timestamp":"2021-04-14T04:31:58+00:00","tags":["info","plugins","crossClusterReplication"],"pid":6,"message":"Your basic license does not support crossClusterReplication. Please upgrade your license."}
{"type":"log","@timestamp":"2021-04-14T04:31:58+00:00","tags":["info","plugins","monitoring","monitoring","kibana-monitoring"],"pid":6,"message":"Starting monitoring stats collection"}
{"type":"log","@timestamp":"2021-04-14T04:31:59+00:00","tags":["warning","plugins","reporting"],"pid":6,"message":"Enabling the Chromium sandbox provides an additional layer of protection."}
{"type":"response","@timestamp":"2021-04-14T04:32:03+00:00","tags":[],"pid":6,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.61.1","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"curl/7.61.1"},"res":{"statusCode":200,"responseTime":88,"contentLength":128251},"message":"GET /app/kibana 200 88ms - 125.2KB"}
{"type":"response","@timestamp":"2021-04-14T04:32:13+00:00","tags":[],"pid":6,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.61.1","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"curl/7.61.1"},"res":
```

Here is my configuration:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ops-gateway
  namespace: istio-system
spec:
  selector:
    istio: ops-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "*"
---
elasticsearchHosts: "https://elasticsearch-master:9200"

replicas: 1

imageTag: "7.12.0"
imagePullPolicy: "Always"

serviceAccount: secretsinvoker

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: user
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: pwd
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey
  - name: 'SERVER_BASEPATH'
    value: "/kibana"

extraVolumes:
  - name: elastic-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "elastic-secrets"
  - name: kibana-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "kibana-secrets"
  - name: elastic-ca
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "elastic-ca-pem"

extraVolumeMounts:
  - mountPath: "/var/elastic/secrets"
    name: elastic-secrets
  - mountPath: "/usr/share/kibana/config/certs"
    name: elastic-ca
  - mountPath: "/var/kibana/secrets"
    name: kibana-secrets

kibanaConfig:
  kibana.yml: |
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs/elasticsearch-ca.pem
      certificate: /usr/share/kibana/config/certs/elasticsearch-ca.pem
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.security.session.idleTimeout: "1h"
    xpack.security.session.lifespan: "30d"
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/elasticsearch-ca.pem
      verificationMode: certificate

protocol: https

service:
  type: ClusterIP
  loadBalancerIP: ""
  port: 443
  nodePort: ""
  labels: {}
  annotations: {}
    # cloud.google.com/load-balancer-type: "Internal"
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    # service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
  loadBalancerSourceRanges: []
    # 0.0.0.0/0
  httpPortName: https
```
