### ISSUE TITLE
Allow using templates to define secrets in logstash chart

### ISSUE THREAD

**Issue by stuart-mclaren-hpe** [elastic/helm-charts#1150]
**Describe the feature:**

It is currently possible to define secrets in the logstash helm chart.
You have two options: (1) a key/value pair (2) reference a secret in a file.

I'd like to add a third option where the value can be interpreted as a template.

In code, this would be a couple of additional lines (in secrets.yaml):

```
data:                                                                           
{{- range $key, $val := .value }}                                               
  {{- if hasSuffix "filepath" $key }}                                           
  {{ $key | replace ".filepath" "" }}: {{ $.Files.Get $val | b64enc | quote }}  
  {{ else if hasSuffix "template" $key }}                                                        <<< new line
  {{ $key | replace ".template" "" }}: {{ tpl $val $ | b64enc | quote }}             <<< new line
  {{ else }}                                                                    
  {{ $key }}: {{ $val | b64enc | quote }}                                       
  {{- end }}                                                                    
{{- end }} 
```

**Describe a specific use case for the feature:**

We use the logstash chart as a dependent chart. This means we have a values.yaml file which "wraps" the values.yaml in the upstream logstash chart. We'd like to provide a simple way to propagate
a value to a secret that will exist in all our deployments.

The values.yaml in our parent chart would look like:

```
  logstash:
    secrets:                                                                      
      - name: logz-token                                                          
        value:                                                                    
          LOGZ_TOKEN.template: "{{ .Values.logstash.token }}"   
```

Consumers of our chart can then simply provide the token value, without having to worry about the specific secret structure (this avoids passing an array index number etc).

`helm install foo bar --set token=secret123`

For example, you could then do

```
  envFrom:                                                                      
    - secretRef:                                                                
        name: logz-token 
```

to have the environment variable in a pod set to the relevant value:

```
LOGZ_TOKEN=secret123
```
