### ISSUE TITLE
elastic/elasticsearch: pods stuck in pending state with  volumeClaimTemplate on AWS  cluster

### ISSUE THREAD

**Issue by ghost** [elastic/helm-charts#1153]
I have setup **kops cluster on aws** and also helm is installed in the cluster.

I am trying to install easltic/elasticsearch using the chart. I need to modify the default volume size for that I have create below `values.yml` file.

```
# Request smaller persistent volume
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
```

This is how I installed it,
```
helm install elasticsearch -n logging elastic/elasticsearch -f values.yml
```
Installation is successful, but now pods are stuck in pending state
```
[ec2-user@ip-my elastic-search]$ kubectl get pods -n logging
NAME                     READY   STATUS    RESTARTS   AGE
elasticsearch-master-0   0/1     Pending   0          6m35s
elasticsearch-master-1   0/1     Pending   0          6m35s
elasticsearch-master-2   0/1     Pending   0          6m35s
```
