### ISSUE TITLE
[LOGTASH] error mount extra volume

### ISSUE THREAD

**Issue by nvthuong1996** [elastic/helm-charts#1182]
**Chart version:** 7.12.1

Error
```
Error: template: elk/charts/logstash/templates/statefulset.yaml:139:14: executing "elk/charts/logstash/templates/statefulset.yaml" at <.Values.extraVolumes>: wrong type for value; expected string; got []interface {} Use --debug flag to render out invalid YAML
```

Value:
```
  extraVolumeMounts:
  - name: email-error-template
    mountPath: /tmp/template
  
  extraVolumes:
  - name: email-error-template
    configMap:
      name: email-error-template
```

**Comment by ebuildy** [comment]
logstash chart requires a string, not an array. Whereas other chart such as ``apm-server`` requires an array .... 

So the correct syntax for logstash is:

```
 extraVolumeMounts: |+
    - name: email-error-template
      mountPath: /tmp/template
  
  extraVolumes: |+
    - name: email-error-template
      configMap:
        name: email-error-template
```

I think this sould be rewritten to handle ``extraVolumeMounts`` /  ``extraVolumes`` as array (like apm-server chart).
