### ISSUE TITLE
Logstash Helm Chart Pipelines aren't actually pipelines

### ISSUE THREAD

**Issue by fxdgear** [elastic/helm-charts#1187]
When given the ability to define `logstashPipelines` via the values.yaml file this isn't really giving the customer the ability to define multiple pipelines. What this is actually doing is allowing the customer to break up their `main` pipeline into multiple files. 

```yaml
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        type => "beats"
        port => "5044"
      }
    }
    output {
      stdout {
        codec => json
      }
    }
  anotherpipeline.conf: |
  input {}
  output {}
```

What happens is all these files get loaded into the `$LOGSTASH_HOME/pipelines` directory, but the `config/pipelines.yaml` is left unaltered. So all these logstash conf files end up loaded in a single pipeline. 

What we need to have happen here is a values override to be declared like: 

```yaml
logstashPipeline:
  - id: mypipeline
    workers: 3
    queue_type: persisted
    config:
      logstash.conf: |
        input {
          beats {
            type => "beats"
            port => "5044"
          }
        }
        output {
          stdout {
            codec => json
          }
        }
  - id: anotherpipeline
    workers: 1
    config:
      anotherpipeline.conf: |
        input {}
        output {}
```

Another reason for this feature change is if there are multiple different deployments of logstash all shipping their monitoring data to the same elasticsearch cluster, then all pipelines end up with the same "name" of `main` which then makes it really hard to monitor each pipeline.

**Comment by fxdgear** [comment]
Closing this issue since @jmlrt showed me a way to define the pipeline.yaml in the `logstashConfig` setting. 

For anyone else who comes here looking a sufficent way to define pipelines would be: 

```yaml
logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
  pipelines.yml: |
    - pipeline.id: uptime
      path.config: "/usr/share/logstash/pipeline/uptime.conf"
    - pipeline.id: w
      path.config: "/usr/share/logstash/pipeline/w.conf"
logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output { stdout { } }
  w.conf: |
    input { exec { command => "w" interval => 30 } }
    output { stdout { } }
```
