### ISSUE TITLE
[kibana] Confusion with ELASTICSEARCH_USERNAME env var

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1239]
**Chart version:** 7.13.0

**Helm Version:** 3.6.0

**Describe the bug:**

Context: use kibana / elasticsearch with security enabled.

As per documentation, https://www.elastic.co/guide/en/kibana/7.13/using-kibana-with-security.html, we must configure kibana like this:

```
elasticsearch.username: "kibana_system"
```

Via Docker, it's possible to configure this via an environnement variable (in this case ``ELASTICSEARCH_USERNAME``).

But the Helm chart is also using ``ELASTICSEARCH_USERNAME`` env var to do the readinessProbe curl auth!

https://github.com/elastic/helm-charts/blob/master/kibana/templates/deployment.yaml#L120

Since ``kibana_system`` user cannot be used to login on Kibana, this will fail and the pod will never become ready.

**values.yaml**

```
  elasticsearchHosts: http://hot-es-client:9200
  extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: hot-elastic-user-kibana-system
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: hot-elastic-user-kibana-system
```

**Steps to reproduce:**

1. Enable / setup elasticsearch security
2. Configure kibana_system user (set password)
3. Add env to values.Yaml 

**Expected behavior:**

Kibana should run and become ready.

**solutions**

Change https://github.com/elastic/helm-charts/blob/master/kibana/templates/deployment.yaml#L120 to use a different env. What about ``KIBANA_USERNAME`` ?
