### ISSUE TITLE
[logstash] Possible defect - No IP assigned?

### ISSUE THREAD

**Issue by lanamoss** [elastic/helm-charts#1246]
Hi, 
I am unsure whether this is a documentation issue or a code issue, but I tried creating a logstash instance (7.13.1) using all the defaults and I get no ClusterIP (`helm install logstash elastic/logstash`). kubectl says the IP is "None". If I manually attach to the container, I can't ping the localhost (Operation not permitted).

I also tried using NodePort with the values below:

```
service:
  type: NodePort
  ports:
    - port: 5000

persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output { elasticsearch { hosts => ["http://10.111.176.118:9200"] index => "strickland" } }
```

To which I got the following line from `kubectl get svc`:

```
logstash-logstash                         NodePort       10.98.132.185    <none>        5000:30205/TCP                  2m37s
```

Port 30205 is open on my host machine:

```
tcp        0      0 0.0.0.0:30205           0.0.0.0:*               LISTEN      0          116888967  -                   
```

Even with this, I can't curl the host machine on port 30205 (connection refused).

Am I missing something?
