### ISSUE TITLE
[kibana] Setting extraEnvs removes NODE_OPTIONS

### ISSUE THREAD

**Issue by orirawlings** [elastic/helm-charts#1265]
**Chart version:**

7.12.0 (though present in 7.13.2 too)

**Kubernetes version:**

Any

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:**

3.6.1

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get values</summary>

```
USER-SUPPLIED VALUES:
elasticsearchHosts: http://elasticsearch-unified-prod-eu-west-1.prod.egencia.cloud:9200
extraEnvs:
- name: ELASTICSEARCH_USERNAME
  valueFrom:
    secretKeyRef:
      key: username
      name: kibana-credentials
- name: ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: kibana-credentials
- name: ENCRYPTION_KEY
  valueFrom:
    secretKeyRef:
      key: encryptionkey
      name: kibana-credentials
imageTag: 7.9.3
kibanaConfig:
  kibana.yml: |
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    xpack.security.audit.enabled: true
    xpack.security.encryptionKey: ${ENCRYPTION_KEY}
    xpack.reporting.encryptionKey: ${ENCRYPTION_KEY}
    xpack.encryptedSavedObjects.encryptionKey: ${ENCRYPTION_KEY}
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs/tls.key
      certificate: /usr/share/kibana/config/certs/tls.crt
protocol: https
replicas: 2
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi
secretMounts:
- name: kibana
  path: /usr/share/kibana/config/certs
  secretName: kibana
service:
  annotations:
    REDACTED
  httpPortName: https
  loadBalancerSourceRanges:
  - REDACTED
  port: 443
  type: LoadBalancer
```

</details>

<details>
<summary>Output of helm get values --all</summary>

```
COMPUTED VALUES:
affinity: {}
elasticsearchHosts: http://elasticsearch-unified-prod-eu-west-1.prod.egencia.cloud:9200
elasticsearchURL: ""
envFrom: []
extraContainers: ""
extraEnvs:
- name: ELASTICSEARCH_USERNAME
  valueFrom:
    secretKeyRef:
      key: username
      name: kibana-credentials
- name: ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: kibana-credentials
- name: ENCRYPTION_KEY
  valueFrom:
    secretKeyRef:
      key: encryptionkey
      name: kibana-credentials
extraInitContainers: ""
fullnameOverride: ""
healthCheckPath: /app/kibana
hostAliases: []
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.9.3
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
  tls: []
kibanaConfig:
  kibana.yml: |
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    xpack.security.audit.enabled: true
    xpack.security.encryptionKey: ${ENCRYPTION_KEY}
    xpack.reporting.encryptionKey: ${ENCRYPTION_KEY}
    xpack.encryptedSavedObjects.encryptionKey: ${ENCRYPTION_KEY}
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs/tls.key
      certificate: /usr/share/kibana/config/certs/tls.crt
labels: {}
lifecycle: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: https
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 2
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi
secretMounts:
- name: kibana
  path: /usr/share/kibana/config/certs
  secretName: kibana
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations:
    REDACTED
  httpPortName: https
  labels: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges:
  - REDACTED
  nodePort: ""
  port: 443
  type: LoadBalancer
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate
```

</details>

**Describe the bug:**

If a user sets `extraEnvs`, it overrides the default `NODE_OPTIONS` that are necessary for capping the node heap and preventing OOMs and frequent crashes/restarts of kibana containers.

The work-around is that the chart user needs to copy the value for `extraArgs` from https://github.com/elastic/helm-charts/blob/a5aa70afe7875731cf910a4e82e1a1c4c82521d6/kibana/values.yaml#L9-L11 and then specify any additional, needed environment variables. This will avoid overwriting the default `NODE_OPTIONS` setting provided by the chart.

**Steps to reproduce:**

1. Set any value for `extraArgs`
2. `helm template` or `helm install` and see that the result no longer has `NODE_OPTIONS`

**Expected behavior:**

Ideally `extraEnvs` default value would be `[]` as it was before #504 and `NODE_OPTIONS` would still be included in the rendered environment variables. That way users wouldn't need to know that they need to duplicate the `NODE_OPTIONS` setting when adding extra environment variables. Basically, merge together default environment variables provided by the chart author with environment variables provided by the user.

**Provide logs and/or server output (if relevant):**

Our kibana containers crash on a consistent basis with the following log messages:
```
<--- Last few GCs --->
[6:0x37c2d20]  1006886 ms: Mark-sweep 1169.4 (1307.6) -> 1169.4 (1291.1) MB, 129.5 / 0.0 ms  (average mu = 0.449, current mu = 0.000) last resort GC in old space requested
[6:0x37c2d20]  1007005 ms: Mark-sweep 1169.4 (1291.1) -> 1169.4 (1287.1) MB, 118.3 / 0.0 ms  (average mu = 0.291, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace =========================================
    0: ExitFrame [pc: 0x1a51bff878a1]
Security context: 0x2e718d31e6c1 <JSObject>
    1: byteLength [0x6e07137a669] [buffer.js:~509] [pc=0x1a51c11c4327](this=0x06e0713540c1 <JSFunction Buffer (sfi = 0x1c6103195ff9)>,string=0x2490c950a4c1 <Very long string[263207194]>,encoding=0x2e718d33ddd9 <String[4]: utf8>)
    2: size [0x145876879989] [/usr/share/kibana/node_modules/hapi/lib/response.js:682] [bytecode=0x1ba4889b9491 offset=71](this=0x2...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8fb090 node::Abort() [/usr/share/kibana/bin/../node/bin/node]
 2: 0x8fb0dc  [/usr/share/kibana/bin/../node/bin/node]
 3: 0xb033ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/share/kibana/bin/../node/bin/node]
 4: 0xb035e4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/share/kibana/bin/../node/bin/node]
 5: 0xef7642  [/usr/share/kibana/bin/../node/bin/node]
 6: 0xf06e5f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/share/kibana/bin/../node/bin/node]
 7: 0xed6a0b v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/share/kibana/bin/../node/bin/node]
 8: 0x1020293 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/share/kibana/bin/../node/bin/node]
 9: 0xb00d54 v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [/usr/share/kibana/bin/../node/bin/node]
10: 0xb0e720 v8::String::Utf8Length() const [/usr/share/kibana/bin/../node/bin/node]
11: 0x9148f9  [/usr/share/kibana/bin/../node/bin/node]
12: 0x1a51bff878a1 
```

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**
