### ISSUE TITLE
Apm server extraVolumeMounts

### ISSUE THREAD

**Issue by miksir** [elastic/helm-charts#1299]
**Chart version:** master

**Kubernetes version:** all

**Helm Version:** all

**Describe the bug:**
https://github.com/elastic/helm-charts/blob/master/apm-server/templates/deployment.yaml#L122
```
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
{{- end }}
```
In this part of template we check extraVolumes but use extraVolumeMounts.  
Is it typo or feature?  
I am using extraVolumes only for extraInitContainers (custom apm server config) so I don't need to use extraVolumeMounts, but as result - invalid YAML because `toYaml extraVolumeMounts` prints "" or null or [] 

**Steps to reproduce:**

Use extraVolumes but don't use extraVolumeMounts, for example

```
extraVolumeMounts: []

extraVolumes:
- name: apm-server-init-config
  configMap:
    name: apm-server-init-config
```

**Expected behavior:**

```
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
{{- end }}
```
