### ISSUE TITLE
keystore item not a string

### ISSUE THREAD

**Issue by mrszop** [elastic/helm-charts#1309]
Hello community,

I'm having a hard time adding s3 credentials to my keystore. I've tried to follow your [keystore guide](https://github.com/elastic/helm-charts/tree/master/elasticsearch#how-to-use-the-keystore) by adding two elements `s3.client.default.access_key` and `s3.client.default.secret_key`  via `kubectl` first and then applying the helm chart. I've tried two different ways. First via file:

```bash
kubectl create secret generic s3-client-default-access-key --from-file=s3.client.default.access_key=./s3.client.default.access_key

kubectl create secret generic s3-client-default-secret-key --from-file=s3.client.default.secret_key=./s3.client.default.secret_key
```

Content of those files are like this:

```bash
cat s3.client.default.access_key                                                                           at 17:09:11
b3v...
cat s3.client.default.secret_key
709...
```

After applying the helm chart I've got a `CrashLoopBackOff` Elasticsearch Cluster. Unfortunately I wasn't able to get always a proper log, but what I saw was this:

```
[2021-07-27T14:46:09,526][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-master-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.repositories.s3.S3RepositoryPlugin]]; nested: InvocationTargetException; nested: IllegalStateException[Secret setting s3.client.default.access_key is not a string];
```

I was like "ok, not a string, but what then!?". I've delete my previously created secrets and created new ones like this:

```bash
kubectl create secret generic s3-client-default-access-key --from-literal=s3.client.default.access_key='b3d...'
kubectl create secret generic s3-client-default-secret-key --from-literal=s3.client.default.secret_key='709...'
```

In both cases I've added the elemets to my `values.yaml`:

```yaml
imageTag: 5.6.16
imagePullSecrets:
  - name: registry-pull-secret
resources:
  requests:
    cpu: "2000m"
    memory: "14Gi"
  limits:
    cpu: "3000m"
    memory: "14Gi"
volumeClaimTemplate:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
imagePullPolicy: Always
esJavaOpts: "-Xmx7g -Xms7g"
esConfig:
  elasticsearch.yml: |
    http.cors:
      enabled: true
      allow-origin: "http://localhost:48080"
      allow-headers : X-Requested-With,Content-Type,Content-Length,Authorization
    xpack.security.enabled: false
nodeSelector:
  dedicated: elasticsearch
tolerations:
  - key: dedicated
    operator: Equal
    value: elasticsearch
    effect: NoSchedule
roles:
  remote_cluster_client: ~
keystore:
  - secretName: s3-client-default-access-key
  - secretName: s3-client-default-secret-key
```

Same error message.

Cheers,
Szop
