### ISSUE TITLE
Create dashboards in kibana for autodiscovered modules

### ISSUE THREAD

**Issue by calind** [elastic/helm-charts#131]
**Describe the feature:**
I'm trying to use the autodiscovery feature for the logs. It work's as advertised, which is great, but the problem is that filebeat is not creating dashboards for autodiscovered logs.

**Describe a specific use case for the feature:**
Set `co.elastic.logs/module: mysql` on the mysql pod and have the dashboard created in kibana.

**Comment by Crazybus** [comment]
Hi Calin!

I haven't tested it out yet, but I think this should already be possible. It looks like you should just be able to [configure the Kibana endpoint](https://www.elastic.co/guide/en/beats/filebeat/current/setup-kibana-endpoint.html) and [enable dashboard management](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-dashboards.html) from beats. 

Something like this: (not tested)
```
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "helm-kibana-default-kibana:5601"
    setup.dashboards.enabled: true
```
    
Could you give this a go and see if it works for you?
