### ISSUE TITLE
Elasticsearch security setting is not working. Elasticsearch docker image ignores ELASTIC_USERNAME

### ISSUE THREAD

**Issue by NgZiming** [elastic/helm-charts#1334]
**Chart version:** 7.14.0

**Kubernetes version:** v1.15.5

**Helm Version:** 3

**Describe the bug:**

Deploy elasticsearch on my k8s, health prob keep failing.

**Steps to reproduce:**

1. custom a elastic-credentials with a ELASTIC_USERNAME that isn't 'elastic'
```yaml
apiVersion: v1
data:
  password: MTIzNDU2 # 123456
  username: YWRtaW4= # admin
kind: Secret
metadata:
  name: elastic-credentials
type: Opaque
```
2. write config
```yaml
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
```
3. install with helm
```bash
helm upgrade --wait --timeout=600s --install -n xxxxxx -f values.yaml xxxx elasticsearch
```

**Expected behavior:**

health prob success

**Any additional context:**

I tried to run the health prob script inside the pod, then i found out that es didn't respect ELASTIC_USERNAME. Health checks would succeed when i used the default username.

```bash
curl -k -XGET -u elastic:123456 'https://127.0.0.1:9200/_cluster/health?wait_for_status=green&timeout=1s'
{"cluster_name":"sg-elasticsearch","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

and i did some research. docker-entrypoint.sh respects ELASTIC_PASSWORD only.

[docker-entrypoint.sh](https://github.com/elastic/elasticsearch/blob/7.14/distribution/docker/src/docker/bin/docker-entrypoint.sh)

Consider remove ELASTIC_USERNAME from the example, or maybe set up a docker-entrypoint.sh that respect ELASTIC_USERNAME in the chart?
