### ISSUE TITLE
Declared `storageClassName` is not applied

### ISSUE THREAD

**Issue by alimoli** [elastic/helm-charts#1374]
**Chart version:**
`7.14.0`

**Kubernetes version:**
`1.20.9`

**Kubernetes provider:**
AKS (Azure Kubernetes Services)

**Helm Version:**
`v3.7.0`

**`helm get release` output**
```helm get values elasticsearch
USER-SUPPLIED VALUES:
antiAffinity: soft
esJavaOpts: -Xmx128m -Xms128m
resources:
  limits:
    cpu: 1000m
    memory: 512M
  requests:
    cpu: 100m
    memory: 512M
volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: standard
```

**Describe the bug:**
`StorageClassName` is set to `standard` when **values.yaml** declares it as `azurefile`.
I expect to claim a `azurefile` storage class and not a `standard`,

**Steps to reproduce:**

`helm upgrade --install elasticsearch elastic/elasticsearch -f values.yaml`

```yaml
# values.yaml

clusterName: "k8s-dev"
nodeGroup: "master"

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "true"
  ingest: "true"
  data: "true"

#Kubernetes replica count for the StatefulSet
replicas: 1
minimumMasterNodes: 1
clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.12.0"
imagePullPolicy: "IfNotPresent"

esJavaOpts: "-Xms512m -Xmx512m"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"

networkHost: "0.0.0.0"

volumeClaimTemplate:
  accessModes:
    - ReadWriteMany
  # Azure Files can be used to mount an SMB 3.0 share backed by an Azure Storage account to pods.
  # Files can be shared across Nodes and Pods.
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi

persistence:
  enabled: true
  labels:
    # Add default labels for the volumeClaimTemplate of the StatefulSet
    enabled: false
  annotations: {}


protocol: http
httpPort: 9200
transportPort: 9300

sysctlVmMaxMapCount: 262144
```

**Expected behavior:**

PVC should be created as an `azurefile`, not a `standard` class that is not present in Azure.
I could create a `standard` class storage in Azure to fix this, but I think it is not so nice.
