### ISSUE TITLE
The filebeat and metricbeat charts define the livenessProbe and readinessProbe but without enabling them in the config

### ISSUE THREAD

**Issue by gwvandesteeg** [elastic/helm-charts#1414]
**Chart version:**

7.15+

**Metricbeat:**
The default values for the configuration in `metricbeat.yml` in the `values.yaml` file does not expose the http endpoint used by the liveness and readiness Probes.  The example configuration should add

```yaml
      # enable the http endpoint for health checks
      http:
        enabled: true
        host: localhost
        port: 5066
```
**Filebeat**
Exactly the same

**Steps to reproduce:**

1. Deploy the chart, you'll see 0/1 on the READY state on the pods because the liveness and readiness probes are failing due to the HTTP endpoint being used in those healtchecks not being enabled.

**Expected behavior:**

The health and readiness checks function correctly.
