### ISSUE TITLE
Use the tpl function for filebeatConfig

### ISSUE THREAD

**Issue by emmanuelCarre** [elastic/helm-charts#1436]
**Describe the feature:**

It will allow the config files to have fields templated out as well.

When creating configmaps from the filebeatConfig defined in values.yaml, it is useful to use the tpl function like this:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}-config
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.filebeatConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}
```

This is a small change, but it would give users a lot more power when supplying configs through the values.yaml.

**Describe a specific use case for the feature:**

We will be able to separate configuration to dedicate file and write something like this:

```yaml
filebeatConfig:
  filebeat.yml: |
    # Insert config here...
```

Someone could do:

```yaml
filebeatConfig:
  filebeat.yml: |
    {{ .Files.get "configs/filebeat.yml" }}
```

Furthermore it will allow the config files to have fields templated out.
