### ISSUE TITLE
Metricbeat Sidecar Issue

### ISSUE THREAD

**Issue by ruwan1235** [elastic/helm-charts#1448]
I used metrictbeat sidecar container for monitor my wildfly pod. Also we used wildyfly helm chart to deploy metricbeat sidecar. 
````
sidecars: 
  - name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.15.2
    imagePullPolicy: Always 
    
    args: [
          "-c", "/usr/share/metricbeat/metricbeat.yml",
          "-e"
          ]
    env:
    - name: ELASTICSEARCH_HOSTS
      value: "10.9.0.156"
    - name: ELASTICSEARCH_PORT
      value: "9200"
````
Now working fine and we can get data using kibana dashboard. Also show data in discover tab.

But we con't enable dashboard yet. Anyone have solution for this? Can we enable configmap for metricbeat.yml ?

**Comment by ebuildy** [comment]
What chart are you talking about?

In the case of logstash, you can easily add a ``metricbeat.yml`` file using ``logstashConfig``:

values.yaml:

```
logstashConfig:
    pipelines.yml: |
      - pipeline.id: main
        path.config: "/usr/share/logstash/pipeline/logstash.conf"

    logstash.yml: |
      http.host: 0.0.0.0
      log.level: info
     
    metricbeat.yml: |
      metricbeat.modules:
      - module: logstash
        metricsets:
        - node
        - node_stats
        period: 120s
        hosts: ["localhost:9600"]
        xpack.enabled: true
      output.elasticsearch:
        hosts: 'http://djobi-metrics-es:9200'
      queue.mem:
        events: 1024
        flush.min_events: 128
        flush.timeout: 5s
```
