### ISSUE TITLE
no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by lapwat** [elastic/helm-charts#1452]
I am trying to install `elastic/kibana` helm chart with custom values:

```sh
helm install -n instances kibana elastic/kibana -f values.yaml  --dry-run --version 7.15.0
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

values.yaml

```yml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - host: my.domain.com
    paths:
    - path: /
tls:
- hosts:
  - my.domain.com
  secretName: certificate-domain
```

I do not understand how this error can be triggered because there is no reference to `networking.k8s.io/v1beta1` in the chart. This issue must have been resolved by #1409
