### ISSUE TITLE
Tighten securityContext to comply with restricted PSS

### ISSUE THREAD

**Issue by seilersTNG** [elastic/helm-charts#1549]
**Describe the feature:**
In the context of Pod Security Policy (PSP) deprecation (https://kubernetes.io/docs/concepts/policy/pod-security-policy/), I tried to enforce the new restricted Pod Security Standard (PSS) (https://kubernetes.io/docs/concepts/security/pod-security-standards/).

for this to work I had to tighten the securityContext for elasticsearch and kibana using version 7.16.3:

elasticsearch:
```
securityContext:
  allowPrivilegeEscalation: false                                                                                                                                                                                                                                             
  privileged: false                                                                                                                                                                                                                                                           
  seccompProfile:
    type: RuntimeDefault
```

kibana:
```
securityContext:
  allowPrivilegeEscalation: false
```

**Describe a specific use case for the feature:**
By adding these configurations to the standard helm chart, people who move to the new pod security standard can directly enforce the restricted pod security standard for the corresponding namespace.
