### ISSUE TITLE
Master Pods not Recovering from Deletion 

### ISSUE THREAD

**Issue by DandyDeveloper** [elastic/helm-charts#155]
**Chart version:**
7.1.0

**Kubernetes version:**
1.12.7

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Bare Metal

**Helm Version:**
2.14.0

**Values.yaml:**
```
elasticsearch-master:
  enabled: true
  replicas: 6
  minimumMasterNodes: 4
  nodeSelector: {role: elasticsearch}
  antiAffinity: "disable"
  roles:
    master: "true"
    ingest: "false"
    data: "false"
```

**Describe the bug:**
After removing any of the masters, the subsequent recovery pod starts successfully, but is unable to reconnect to the cluster. 

I can't figure out if this is because there isn't a nominated master, or because of some other issue, I'm trying to find out from the log what might be the problem.

**Steps to reproduce:**
1. Run master nodes using above config on empty cluster
2. Wait for them to start successfully
3. Delete pod.

**Expected behavior:**
Pod recovers and connects to the cluster successfully. 

**Provide logs and/or server output (if relevant):**
Pending... 

**Any additional context:**
Important note is we are running bare metal, but really the behaviour doesn't seem to be a Kubernetes problem at this point.
