### ISSUE TITLE
filebeat is not capturing apmserver logs

### ISSUE THREAD

**Issue by Dinesh558** [elastic/helm-charts#1571]
filebeat is not capturing apmserver pod logs and its own logs.

Installed filebeat version -> helm install filebeat elastic/filebeat --version 7.15.0

FIlebeat configmap
```yaml
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        stream: stdout
        multiline.type: pattern
        multiline.pattern: '^[[:space:]]+|^java\.|^com\.|^<|^$'
        multiline.negate: false
        multiline.match: after
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"

      logging.level: debug
      setup.ilm.enabled: false
      setup.template.enabled: false

      processors:
      - dissect:
          tokenizer: "%{} [%{loglevel}] [%{threadid}] [%{class}] {%{tenantid}} {%{sessionid}} {%{requestid}}"
          field: "message"
          target_prefix: ""
          ignore_failure: true
          overwrite_keys: true
          trim_values: "all"

      output.elasticsearch:
        bulk_max_size: 1200
        hosts: ['${ELASTICSEARCH_SERVICE}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        index: "dev-%{[kubernetes.namespace]:filebeat}-%{+yyyy.MM.dd}"
```

Installed APM Server via custom charts ->

**configmap**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  namespace: {{ .Values.namespace }}
  labels:
    app: apm-server
data:
  apm-server.yml: |-
    apm-server: 
      host: "localhost:8200"
    output.elasticsearch:
      enabled: true
      index: "apm-{{ .Values.namespace }}-%{[observer.version]}-%{[processor.event]}-%{+yyyy.MM.dd}"
      hosts: ["{{ .Values.config.elasticsearch_url }}"]
      username: "${ELASTICSEARCH_USER}"
      password: "${ELASTICSEARCH_PASSWORD}"
      ssl.enabled: true
      ssl.verification_mode: none
      bulk_max_size: 5120
    setup.template.name: "apm-%{[observer.version]}"
    setup.template.pattern: "apm-*"`
```

**APM deployment**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: {{ .Values.namespace }}
  labels:
    app: apm-server
spec:
  replicas: {{ .Values.replicas | default "1" }}
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - "-e"
          #- "-d"
          # - "*"
        livenessProbe:
          httpGet:
            path: /
            port: 8200
          timeoutSeconds: 60
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8200
          initialDelaySeconds: 60
        name: apmserver
        ports:
        - containerPort: 8200
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: config
          mountPath: /etc/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
        env:
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: elasticsearch_password
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: elasticsearch_user
        - name: APM_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: apm_server_token
      volumes:
      - name: config
        configMap:
          name: apm-server-config
```

**Comment by Dinesh558** [comment]
Deployed configuration

**FIlebeat configmap**
```yaml
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        stream: stdout
        multiline.type: pattern
        multiline.pattern: '^[[:space:]]+|^java\.|^com\.|^<|^$'
        multiline.negate: false
        multiline.match: after
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"

      logging.level: debug
      setup.ilm.enabled: false
      setup.template.enabled: false

      processors:
      - dissect:
          tokenizer: "%{} [%{loglevel}] [%{threadid}] [%{class}] {%{tenantid}} {%{sessionid}} {%{requestid}}"
          field: "message"
          target_prefix: ""
          ignore_failure: true
          overwrite_keys: true
          trim_values: "all"

      output.elasticsearch:
        bulk_max_size: 1200
        hosts: ['${ELASTICSEARCH_SERVICE}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        index: "hcs-dev-%{[kubernetes.namespace]:filebeat}-%{+yyyy.MM.dd}"
```

**APM configMap**
 ```yaml
  apm-server.yml: |-
    apm-server: 
      host: "localhost:8200"
    output.elasticsearch:
      enabled: true
      index: "apm-{{ .Values.namespace }}-%{[observer.version]}-%{[processor.event]}-%{+yyyy.MM.dd}"
      hosts: ["{{ .Values.config.elasticsearch_url }}"]
      username: "${ELASTICSEARCH_USER}"
      password: "${ELASTICSEARCH_PASSWORD}"
      ssl.enabled: true
      ssl.verification_mode: none
      bulk_max_size: 5120
    setup.template.name: "apm-%{[observer.version]}"
    setup.template.pattern: "apm-*"
```

**APM deployment**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: {{ .Values.namespace }}
  labels:
    app: apm-server
spec:
  replicas: {{ .Values.replicas | default "1" }}
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - "-e"
          #- "-d"
          # - "*"
        livenessProbe:
          httpGet:
            path: /
            port: 8200
          timeoutSeconds: 60
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8200
          initialDelaySeconds: 60
        name: apmserver
        ports:
        - containerPort: 8200
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: config
          mountPath: /etc/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
        env:
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: elasticsearch_password
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: elasticsearch_user
        - name: APM_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: apm-server
              key: apm_server_token
      volumes:
      - name: config
        configMap:
          name: apm-server-config
```

**Comment by framsouza** [comment]
is it only happening with apm-server output logs? or is it not collect any logs at all?
have you double check if your `path.logs` is ` logs_path: "/var/log/containers/`
as per your settings? 

```
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
```
