### ISSUE TITLE
Improve integration of value `elasticsearchHosts` with parent/sibling charts

### ISSUE THREAD

**Issue by elouanKeryell-Even** [elastic/helm-charts#1583]
I am deploying Kibana chart as part of a wider parent chart, where multiple sub-charts use the same `elasticsearchHosts` value

I want to be able to define the value once for all the subcharts

Currently I don't think it is possible, bc I have to do something like this in the parent chart values':

```yaml
kibana:
  elasticsearchHosts: <blabla>
custom-subchart-1:
  elasticsearchHosts: <blabla>
custom-subchart-2:
  elasticsearchHosts: <blabla>
```

Would it be possible to implement a workaround to avoid duplicating the value?

I am thinking about the following work-around: Allow templating on value `elasticsearchHosts`

Something like:

```yaml
env:
- name: ELASTICSEARCH_HOSTS
  value: "{{ tpl .Values.elasticsearchHosts $ }}"
```

This would then allow to do this:

```yaml
global:
  elasticsearchHosts: <blabla>

kibana:
  elasticsearchHosts: '{{ .Values.global.elasticsearchHosts }}'
custom-subchart-1:
  elasticsearchHosts: '{{ .Values.global.elasticsearchHosts }}'
custom-subchart-2:
  elasticsearchHosts: '{{ .Values.global.elasticsearchHosts }}'
```

What is your opinion on the matter?
