### ISSUE TITLE
Headless service doesn't respect namespaces

### ISSUE THREAD

**Issue by phoenix-bjoern** [elastic/helm-charts#1647]
**Chart version: >=7.15.0**

**Kubernetes version: >= 1.20**

**Kubernetes provider: irrelevant**

**Helm Version: >=3.5.0**

**Describe the bug:**

Despite the elastisearch-master service the headless service doesn't respect Helm release (https://github.com/elastic/helm-charts/blob/main/elasticsearch/templates/service.yaml#L73). When deployment the same application to multiple namespaces the headless service might select Elasticsearch instances of foreign namespaces which is an unexpected behavior.

The headless service selector should be extended to also have the release and the chart version:

```
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
```

**Steps to reproduce:**

1. Create two namespaces ns-1 and ns-2
2. Deploy Elasticsearch to both namespaces
3. Check the "elasticsearch-headless" IPs and it should list ES instances from both namespaces.

**Expected behavior:**

"elasticsearch-headless" should only select ES instances within it's namespace.
