### ISSUE TITLE
values.yml --> clusterRoleRules useful?

### ISSUE THREAD

**Issue by share-me** [elastic/helm-charts#1666]
**Chart version:**
7.17.3

**Kubernetes version:**
1.21

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS

**Helm Version:**
3.6.3

**Describe the bug:**

values.yml offers to set clusterRoleRules, but if you change its value then  Filebeat can't work properly anymore

```yaml
clusterRoleRules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
```

**Expected behavior:**

keep ClusterRoleRules hardcoded
Maybe to add something like clusterRoleRulesExtra

**Provide logs and/or server output (if relevant):**

E0621 14:35:49.835562       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes "ip-<hidden>.compute.internal" is forbidden: User "system:serviceaccount:<hidden>cannot list resource "nodes" in API group "" at the cluster scope

```
```

**Any additional context:**
