### ISSUE TITLE
node.roles doesn't work on ES 8.4.0

### ISSUE THREAD

**Issue by piyushkp** [elastic/helm-charts#1686]
**Chart version: latest

**Kubernetes version: latest

**Kubernetes provider:AKS

**Helm Version:latest

i'm upgrading from ES 8.2.0 to 8.4.0 and coordinator nodes failing with: (it worked fine in 8.2.0)

`Exception in thread "main" org.elasticsearch.ElasticsearchParseException: null-valued setting found for key [node.roles] found at line number [9], column number [12]
	at org.elasticsearch.common.settings.Settings.validateValue(Settings.java:768)
	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:743)
	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1190)
	at org.elasticsearch.node.InternalSettingsPreparer.loadOverrides(InternalSettingsPreparer.java:143)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:53)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)`

    ```
        roles: []
        # For client nodes, we also need to add an empty node.roles in elasticsearch.yml
        # This is due to https://github.com/elastic/helm-charts/pull/1186#discussion_r631225687
        esConfig:
          elasticsearch.yml: |
            node.roles: []
    ```
