### ISSUE TITLE
Logstash template for ServiceAccount has annotations, twice

### ISSUE THREAD

**Issue by woutersmit** [elastic/helm-charts#1718]
**Chart version:**
logstash 7.17.3

**Kubernetes version:**
does not apply

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
does not apply

**Helm Version:**
3.9.0

**`helm get release` output**

<details>
<summary>Output of helm get release</summary>
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "salvador-logstash"
  annotations:
  labels:
    app: "salvador-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "salvador"
  annotations:
    annotation1: "value1"
```

</details>

**Describe the bug:**
The logstash template for ServiceAccount has `annotations` twice. You can workaround this by leaving either `.Values.rbac.serviceAccountAnnotations` or `.Values.rbac.annotations` empty, but this is only because kubeapi is forgiving. Invalid yaml is being generated.

**Steps to reproduce:**

1. Any basic release that has rbac: create: true

**Expected behavior:**
Valid yaml is being generated.
