### ISSUE TITLE
Kibana helm installation fails with UNABLE_TO_GET_ISSUER_CERT

### ISSUE THREAD

**Issue by VigneshOK10** [elastic/helm-charts#1740]
I was trying to deploy kibana helm chart where Elasticsearch was already deployed and running fine.
kibana helm chart - [helm-charts/kibana at main · elastic/helm-charts · GitHub 1](https://github.com/elastic/helm-charts/tree/main/kibana)

After helm installation the deployment failed due pre-install-job failure.
When I described logs for the same below is the output

master-vm:~/elk/helm-charts # kubectl logs pre-install-kibana-kibana-wbr8z -n elk
Creating a new Elasticsearch token for Kibana
Cleaning previous token
statusCode: 200
Creating new token
statusCode: 200
Creating K8S secret
POST undefined failed: unable to get issuer certificate
Error: unable to get issuer certificate
at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
at TLSSocket.emit (node:events:513:28)
at TLSSocket._finishInit (node:_tls_wrap:953:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
code: 'UNABLE_TO_GET_ISSUER_CERT'
}

can someone help on what went wrong in Creating K8S secret??

**Comment by DmitriyEsin** [comment]
The same, but I get 
```
Creating a new Elasticsearch token for Kibana
Cleaning previous token
DELETE undefined failed:  self signed certificate
Error: self signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:953:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

I used [this](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-custom-http-certificate.html) manual to create self-signed certs with my custom DNS records 

configs:
```
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: true
      xpack.security.transport.ssl.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.transport.ssl.verification_mode: "certificate"
      xpack.security.transport.ssl.key: "/usr/share/elasticsearch/config/certs/tls.key"
      xpack.security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certs/tls.crt"
      xpack.security.transport.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certs/ca.crt"
      xpack.security.http.ssl.key: "/usr/share/elasticsearch/config/certs/tls.key"
      xpack.security.http.ssl.certificate: "/usr/share/elasticsearch/config/certs/tls.crt"
      xpack.security.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certs/ca.crt"
```
```
  kibanaConfig:
    kibana.yml: |
      security.enabled: true
      security.transport.ssl.enabled: true
      security.http.ssl.enabled: true
      security.transport.ssl.key: "/usr/share/elasticsearch/config/certs/tls.key"
      security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certs/tls.crt"
      security.http.ssl.key: "/usr/share/elasticsearch/config/certs/tls.key"
      security.http.ssl.certificate: "/usr/share/elasticsearch/config/certs/tls.crt"
```

```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: elasticsearch
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-master-certs
  namespace: elasticsearch
spec:
  isCA: true
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master:9200
    - elasticsearch-master.elasticsearch
    - elasticsearch-master.elasticsearch:9200
    - elasticsearch-master.elasticsearch.svc
    - elasticsearch-master.elasticsearch.svc:9200
    - elasticsearch-master.elasticsearch.svc.cluster.local
    - elasticsearch-master.elasticsearch.svc.cluster.local:9200
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: elasticsearch-master-certs
  subject:
    organizations:
      - org
```
