### ISSUE TITLE
Elasticsearch install plugin

### ISSUE THREAD

**Issue by Braineanear** [elastic/helm-charts#1743]
**Chart version: 8.4.2**

**Kubernetes version: 1.23.11-gke.300**

**Kubernetes provider: GKE **

**Helm Version: 3.8.2**

**Describe the bug:**
I'm trying to install elasticsearch plugin which is "analysis-smartcn", so i used initContainer to install it before running the elasticsearch container, and it worked successfully but what i don't understand is: when i check the installed plugins in the nodes i find nothing.
But when installed the plugin manually in the node i find the plugin installed but i should restart the elastic node so the plugin could work.
This is the elastic values i use to run using helm in the cluster.

```
imageTag: "8.4.2"

extraInitContainers:
  - name: "install-plugins"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.2"
    command:
    - sh
    - -c
    - |
      bin/elasticsearch-plugin install analysis-smartcn
```
and this is the command i run 
`helm upgrade elasticsearch ./elastic-charts/elasticsearch -n elastic --values ./elastic/elasticsearch-values.yaml`

When i go into the pod shell in kubernetes and checks the plugins directory i get nothing in the directory
but when i run `bin/elasticsearch-plugin install analysis-smartcn` i find the the plugin directory.
