### ISSUE TITLE
Unable to deploy Elasticsearch 8 with helm as single node

### ISSUE THREAD

**Issue by robertvanloenhout** [elastic/helm-charts#1759]
I'd like to deploy Elasticsearch 8.5.1 using helm and only use a single node to reduce memory usage on minikube.
This issue is similar to https://github.com/elastic/helm-charts/issues/312, but I'll summarize it here because that issue is closed
because originally it was not an issue regarding Elasticsearch 8.

The deployment is on minikube 1.28.0 with helm 3.8.2

When I set replicas to 1 then elasticsearch pod will produce these warning messages and never become operational:
```
master not discovered or elected yet, an election requires at least 2 nodes
```
We can set discovery type to single-node by adding it to the values file

We can do that like this:
```
esConfig:
  elasticsearch.yml: |
    discovery:
      type: single-node
```

Or we can do it like this:

```
extraEnvs:
  - name: discovery.type
    value: single-node
```

This produces the following error:
```
setting [cluster.initial_master_nodes] is not allowed when [discovery.type] is set to [single-node]
```

We can try setting the initial master nodes it to empty like this:
```
esConfig:
  elasticsearch.yml: |
    discovery:
      type: single-node
    cluster:
      initial_master_nodes: ""
```

This still produce the following error:
```
setting [cluster.initial_master_nodes] is not allowed when [discovery.type] is set to [single-node]
```

We can also try it like this:
```
extraEnvs:
  - name: discovery.type
    value: single-node
  - name: cluster.initial_master_nodes
    value: ""
```
This will produce this error:
```
null-valued setting found for key [cluster.initial_master_nodes]
```

We can try setting the initial master nodes to null like this:
```
esConfig:
  elasticsearch.yml: |
    discovery:
      type: single-node
    cluster:
      initial_master_nodes: null
```
or like this:
```
extraEnvs:
  - name: discovery.type
    value: single-node
  - name: cluster.initial_master_nodes
    value: null
```
Either way the elasticsearch pod will faill immediately with the following error:
```
null-valued setting found for key [cluster.initial_master_nodes] found
```

**Comment by dpfaffenbauer** [comment]
I figured it out:

```yaml
values:
      roles: []
      extraEnvs:
        - name: discovery.type
          value: single-node
        - name: node.roles
          value: master,data,data_content,data_hot,data_warm,data_cold,ingest,ml,remote_cluster_client,transform
```
