### ISSUE TITLE
basePath can not work

### ISSUE THREAD

**Issue by leveryd** [elastic/helm-charts#1761]
**Chart version:**

8.5.1

**Kubernetes version:**

v1.21.5

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

self-host

**Helm Version:**

v3.8.0

**Describe the bug:**

**Steps to reproduce:**

1. in values.yaml, i configure kibana as below

```
kibana:
  elasticsearchHosts: "https://elasticsearch-master:9200"
  kibanaConfig:
     kibana.yml: |
      server.basePath="/kibana"
      server.name="dev.com"
      server.host="0"
```
2. configure ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: dev.com
      http:
        paths:
          - path: /kibana(/|$)(.*) # match all paths that begin with /kibana/
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-kibana   # name of the service
                port:
                  number: 5601
```

**Expected behavior:**

I can normally access kibana ui on http://dev.com:{ingress-port}/kibana.

But acctually, when i visit 'http://dev.com:{ingress-port}/kibana', i will be redirected to 'http://dev.com:{ingress-port}/login' and then response status code will be 404.
