### ISSUE TITLE
[Kibana] 8.5.1 Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition

### ISSUE THREAD

**Issue by zulfikar4568** [elastic/helm-charts#1765]
**Chart version**
```
8.5.1
```

**Kubernetes Version**
```
clientVersion:
  buildDate: "2022-12-08T10:15:02Z"
  compiler: gc
  gitCommit: 804d6167111f6858541cef440ccc53887fbbc96a
  gitTreeState: clean
  gitVersion: v1.25.5
  goVersion: go1.19.4
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-09-21T14:27:13Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/arm64
```

**Kubernetes provider:** Docker Desktop M1

**Helm Version:** 
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```

**`helm get release` output**
<summary>Output of helm get release</summary>

```
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
```
<img width="866" alt="image" src="https://user-images.githubusercontent.com/64786139/215767628-31f47348-00da-4eb3-93b6-66618f74cb8b.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/64786139/216823752-715e9517-8cee-47c6-9d10-8ada2e4311c8.png">

**Describe the bug:**

**Steps to reproduce:**
```
helm install kibana elastic/kibana --namespace elastic --debug
```

**Expected behavior:**
