### ISSUE TITLE
Cannot enable Metricbeat modules

### ISSUE THREAD

**Issue by ladybird17** [elastic/helm-charts#1782]
**Chart version:8.5.1**

**Kubernetes version:1.26.1**

**Kubernetes provider:** 

**Helm Version:3.9.1**

**Describe the bug:**

**Steps to reproduce:**

1. set module nginx in values.yaml

```
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.config.modules:
      - module: nginx
        enabled: true
        metricsets: ["stubstatus"]
        period: 10s
        hosts: ["http://nginxName:80"]
      output.logstash:
        hosts: ["logstashIP:5044"]
```
2. run metricbeat
3. then I checked in the path (/usr/share/metricbeat/modules.d), nginx module is still disabled
![image](https://user-images.githubusercontent.com/73573872/221425939-5895b065-c557-4906-bad7-15208fe4d814.png)

**Expected behavior:**
nginx module enabled
