### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by lknite** [elastic/helm-charts#1789]
**Chart version:**
8.5.1

**Kubernetes version:**
v1.25.7

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kubeadm

**Helm Version:**
v3.10.3+g835b733

**values.yaml**
```
kibana:

  elasticsearchHosts: https://elasticsearch-master.elasticsearch.svc:9200

  ingress:
    enabled: true
    className: "nginx"
    pathtype: ImplementationSpecific
    annotations:
      cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
      cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
```

**Describe the bug:**
Initial kibana deployment job is not successful though I've deployed the certs and credentials from the elasticsearch deployment into the kibana deployment.

**Steps to reproduce:**

1. helm install with specified values
2. get certs and credential secrets from elasticsearch deployment, clean up for kibana
3. deploy certs and credential secrets
4. watch logs and see job starts to do something now that the certs & secrets are present, pods keep failing with above error

**Expected behavior:**
Successful initial kibana deployment

**Provide logs and/or server output (if relevant):**
```
Creating a new Elasticsearch token for Kibana
Cleaning previous token
DELETE undefined failed:  unable to verify the first certificate
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:953:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**Any additional context:**
I am assuming the secrets in the elasticsearch deployment are the same secrets I'm supposed to be deploying in the kibana deployment.

**Comment by lknite** [comment]
$ more secret-elasticsearch-master-credentials.yaml 
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch-master-credentials
data:
  password: <snip>
  username: <snip>
```

$ more secret-elasticsearch-master-certs.yaml 
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch-master-certs
data:
  ca.crt: <snip>
```
