### ISSUE TITLE
kibana cannot be installed, output self signed certificate in certificate chain

### ISSUE THREAD

**Issue by hoorayman** [elastic/helm-charts#1792]
**Chart version:**

Kubernetes version: v1.23.10

Kubernetes provider: native kubernetes

Helm Version: v3.11.0-rc.1

Describe the bug:
kibana cannot be installed, output self signed certificate in certificate chain

Steps to reproduce:
1. prepare custom values.yaml called kibanavalues.yml
2. helm install -f kibanavalues.yml kibana-n1 -n middleware-elasticsearch-n1 ./helm-charts/kibana

Content of kibanavalues.yml:
```yaml
elasticsearchHosts: "https://elasticsearch-master.middleware-elasticsearch-n1.svc:9200"
elasticsearchCertificateSecret: elastic-certificate-crt
elasticsearchCertificateAuthoritiesFile: elastic-certificate.crt

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null

kibanaConfig:
  kibana.yml: |
    elasticsearch.username: "elastic"
    elasticsearch.password: "dgR2bjBW6yxBc2X653du"
    elasticsearch.ssl.verificationMode: none
    server.ssl.enabled: false
    server.rewriteBasePath: false
```

Expected behavior:
installed successfully

But Error occured and Output:

Creating a new Elasticsearch token for Kibana
Cleaning previous token
DELETE undefined failed:  self signed certificate in certificate chain
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:953:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
