### ISSUE TITLE
Filebeat Crashlooping when using autodiscover

### ISSUE THREAD

**Issue by Vandersteen** [elastic/helm-charts#228]
**Chart version:**
filebeat-7.2.0

**Kubernetes version:**
v1.12.7

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Azure AKS

**Helm Version:**
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**`helm get release` output**
e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
REVISION: 1
RELEASED: Sat Jul 20 17:35:55 2019
CHART: filebeat-7.2.0
USER-SUPPLIED VALUES:
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    setup.dashboards.enabled: true
    logging.level: info
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          include_annotations:
          - "*"
      processors:
        - add_cloud_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

COMPUTED VALUES:
extraEnvs: []
extraVolumeMounts: []
extraVolumes: []
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    setup.dashboards.enabled: true
    logging.level: info
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          include_annotations:
          - "*"
      processors:
        - add_cloud_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
fullnameOverride: ""
hostPathRoot: /var/lib
image: docker.elastic.co/beats/filebeat
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.2.0
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
managedServiceAccount: true
nameOverride: ""
podAnnotations: {}
podSecurityContext:
  privileged: false
  runAsUser: 0
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
resources:
  limits:
    cpu: 1000m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
secretMounts: []
serviceAccount: ""
terminationGracePeriod: 30
tolerations: []
updateStrategy: RollingUpdate

HOOKS:
MANIFEST:

---
# Source: filebeat/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-filebeat-config
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.2.0"
    heritage: "Tiller"
    release: "filebeat"
data:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    setup.dashboards.enabled: true
    logging.level: info
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          include_annotations:
          - "*"
      processors:
        - add_cloud_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.2.0"
    heritage: "Tiller"
    release: "filebeat"
---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat-filebeat-cluster-role
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.2.0"
    heritage: "Tiller"
    release: "filebeat"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat-filebeat-cluster-role-binding
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.2.0"
    heritage: "Tiller"
    release: "filebeat"
roleRef:
  kind: ClusterRole
  name: filebeat-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-filebeat
  namespace: elastic
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.2.0"
    heritage: "Tiller"
    release: "filebeat"
spec:
  selector:
    matchLabels:
      app: "filebeat-filebeat"
      release: "filebeat"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:

        configChecksum: 2f71c2cbbe977668e5622a431487258fb141621324eb281899e3fdd8c569674
      name: "filebeat-filebeat"
      labels:
        app: "filebeat-filebeat"
        chart: "filebeat-7.2.0"
        heritage: "Tiller"
        release: "filebeat"
    spec:
      serviceAccountName: filebeat-filebeat
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-filebeat-config
      - name: data
        hostPath:
          path: /var/lib/filebeat-filebeat-elastic-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: "filebeat"
        image: "docker.elastic.co/beats/filebeat:7.2.0"
        imagePullPolicy: "IfNotPresent"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false
          runAsUser: 0

        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # Necessary when using autodiscovery; avoid mounting it otherwise
        # See: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true
```

**Describe the bug:**
The pods are 'crashlooping' with the following error message:

```
2019-07-20T15:38:04.155Z	ERROR	[autodiscover]	cfgfile/list.go:96	Error creating runner from config: input outlet closed
2019-07-20T15:38:04.155Z	INFO	log/input.go:719	input outlet closed
2019-07-20T15:38:04.155Z	ERROR	log/input.go:175	Problem putting initial state: input outlet closed
2019-07-20T15:38:04.155Z	ERROR	[autodiscover]	cfgfile/list.go:96	Error creating runner from config: input outlet closed
2019-07-20T15:38:04.157Z	INFO	[monitoring]	log/log.go:153	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":70,"time":{"ms":79}},"total":{"ticks":460,"time":{"ms":473},"value":460},"user":{"ticks":390,"time":{"ms":394}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":9},"info":{"ephemeral_id":"68764043-ef41-447b-8de0-9d1113343532","uptime":{"ms":39992}},"memstats":{"gc_next":4722368,"memory_alloc":3851424,"memory_total":59269256,"rss":40427520},"runtime":{"goroutines":20}},"filebeat":{"events":{"active":83,"added":83},"harvester":{"open_files":3,"running":0}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"elasticsearch"},"pipeline":{"clients":1,"events":{"active":0,"filtered":83,"total":83}}},"registrar":{"states":{"current":45},"writes":{"success":1,"total":1}},"system":{"cpu":{"cores":2},"load":{"1":0.25,"15":0.4,"5":0.26,"norm":{"1":0.125,"15":0.2,"5":0.13}}}}}}
2019-07-20T15:38:04.157Z	INFO	[monitoring]	log/log.go:154	Uptime: 39.992150783s
2019-07-20T15:38:04.157Z	INFO	[monitoring]	log/log.go:131	Stopping metrics logging.
2019-07-20T15:38:04.157Z	INFO	instance/beat.go:431	filebeat stopped.
```

**Steps to reproduce:**

1. install elastic search & kibana from this repo
2. install filebeat from this repo with configuration:

**values.yaml**
```
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    setup.dashboards.enabled: true
    logging.level: info
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          include_annotations:
          - "*"
      processors:
        - add_cloud_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

3. run `helm install --name filebeat elastic/filebeat -f values.yaml`
4. Wait a few minutes 
5. Run `kubectl get pods` 
6. See

```
filebeat-filebeat-28tk8         0/1     CrashLoopBackOff   5          4m37s
filebeat-filebeat-2skh9         0/1     CrashLoopBackOff   5          4m36s
filebeat-filebeat-gh7hp         0/1     CrashLoopBackOff   5          4m36s
filebeat-filebeat-nrngv         0/1     CrashLoopBackOff   5          4m36s
filebeat-filebeat-wr6jg         1/1     Running            5          4m36s
```

**Expected behavior:**
Not crash looping

**Provide logs and/or server output (if relevant):**
[filebeat-filebeat-gh7hp.log](https://github.com/elastic/helm-charts/files/3413762/filebeat-filebeat-gh7hp.log)

**Additional**

To our nginx-ingress-controller's deployment i've added:

```
Pod Template:
  Labels:           app=nginx-ingress
                    component=controller
                    release=nginx
  Annotations:      co.elastic.logs/fileset.stderr: error
                    co.elastic.logs/fileset.stdout: access
                    co.elastic.logs/module: nginx
```

**Comment by Crazybus** [comment]
I think this should be `add_kubernetes_metadata` not `add_cloud_metadata`. 

```
      processors:
        - add_cloud_metadata:
            in_cluster: true
```

If you really do want the cloud metadata and not the kubernetes metadata then you need to remove the `in_cluster: true` which is not valid for `add_cloud_metadata`.

**Comment by Vandersteen** [comment]
Still crashlooping

Runned it with the following configuration:

```
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    setup.dashboards.enabled: true
    logging.level: debug
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
      processors:
        - add_kubernetes_metadata

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

**Logs**
[filebeat-filebeat-kb78r.log](https://github.com/elastic/helm-charts/files/3418281/filebeat-filebeat-kb78r.log)

**Comment by Vandersteen** [comment]
For some reason removing the setup.dashboards makes it work:

```
filebeatConfig:
  filebeat.yml: |
    setup.kibana.host: "http://kibana-kibana:5601"
    logging.level: info
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

However, I am now facing another issue, the nginx logs are stored twice it seems.

Once with:

```
Provided Grok expressions do not match field value: [10.240.0.6 - [10.240.0.6] - - [22/Jul/2019:16:45:47 +0000] \"GET /api/test HTTP/1.1\" 401 0 \"-\" \"PostmanRuntime/7.15.0\" 2074 0.002 [default-test] 10.244.7.149:80 0 0.000 401 d6b1a2f8e248a9ff0cd4131d60e63798]
```

And once with mapped fields - most seem correct but still weird.

I'm assuming the 'default' nginx module's grok in filebeat is not adapted for nginx-ingress logs ?
