### ISSUE TITLE
Prometheus-operator support

### ISSUE THREAD

**Issue by desaintmartin** [elastic/helm-charts#231]
Hello guys,
Do you plan to support prometheus-operator specific things like ServiceMonitor or PrometheusRule? If so, would you accept PR for this?

**Comment by Crazybus** [comment]
No plans to do this. It also feels kind of weird to manage thirdPartyResources for a specific monitoring tool directly in an unrelated helm chart. It seems like most of the charts doing this are actually hard-coding the monitoring rules into the chart too. Going down this path would mean there would be a future where a whole bunch of thirdPartyResources were being defined and managed. Not only would that be very hard to test and support, it would also get really messy. 

How would you feel about having a more generic value that allows a user to specify whatever templated resources they want? This would allow them to specify thirdPartyResources with templating and define it exactly how they want without adding any extra complexity to the chart.

**Comment by desaintmartin** [comment]
I understand.

With the current state of helm, wouldn't adding thirdPartyResources with templating become a mess to maintain and understand?

**Comment by Crazybus** [comment]
So I didn't mean specifically trying to template thirdPartyResources. More just giving a free form variable for users to dump other templatable resources for it to be managed by the chart itself.

So having a separate file that includes a variable which can contain templating: 
```
{{ tpl .Values.extraYaml . }}
```

The user could then do something like (this is just a copy pasted example that isn't tested)

```
extraYaml: |
  ---
  apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    name: {{ template "fullname" . }}
    labels:
      "app.kubernetes.io/name": '{{ template "name" .}}'
      "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
      "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
      "app.kubernetes.io/instance": "{{ .Release.Name }}"
      "app.kubernetes.io/component": "{{ .Values.master.componentName }}"
  spec:
    groups:
  {{ toYaml .Values.prometheus.alertingrules | indent 2 }}
```

So nothing specific about thirdPartyResources or PrometheusRule.
