### ISSUE TITLE
Wrong parameter reference for secretMounts

### ISSUE THREAD

**Issue by maximelenair** [elastic/helm-charts#233]
**Chart version:** 7.2.1

**Describe the bug:**
secretMounts are parameterised with:

```yaml
secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/filebeat/config/certs
```

However `secretMounts.secretName` is not user **anywhere**.
In my opinion it was intended to be used in the following snippet:

```yaml
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }} # This should be `{{ .secretName }}`
        {{- end }}
```

In all the examples and in the test, `secretMounts.name` and `secretMounts.secretName` always have the same value, which hides the issue.

I don't think this has any impact (as `name` and `secretName` can always have the same value?) however it is quite confusing and leads to some wasted time when setting `name` and `secretName` to different value (esp. if `name` is an existing secret in k8s).
