### ISSUE TITLE
SSL error encrypting communication between browser and Kibana

### ISSUE THREAD

**Issue by dcvtruong** [elastic/helm-charts#275]
**Chart version:**
7.3.0
**Kubernetes version:**
1.13.10
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Kubespray
**Helm Version:**
2.13
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
REVISION: 1
RELEASED: Wed Sep 11 20:26:24 2019
CHART: kibana-7.3.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
antiAffinity: hard
antiAffinityTopologyKey: kubernetes.io/hostname
elasticsearchHosts: http://elasticsearch-master:9200
elasticsearchURL: ""
extraEnvs: []
fullnameOverride: ""
healthCheckPath: /app/kibana
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.3.0
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
kibanaConfig:
  kibana.yml: |
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/config/certs/kibana-kibana.key
    server.ssl.certificate: /usr/share/kibana/config/certs/kibana-kibana.crt
labels: {}
maxUnavailable: 1
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500m
secretMounts:
- name: kibana-ssl
  path: /usr/share/kibana/config/certs
  secretName: kibana-ssl
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  nodePort: 30999
  port: 5601
  type: NodePort
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate

HOOKS:
MANIFEST:

---
# Source: kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-kibana-config
  labels:
    app: kibana
    release: "kibana"
data:
  kibana.yml: |
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/config/certs/kibana-kibana.key
    server.ssl.certificate: /usr/share/kibana/config/certs/kibana-kibana.crt
---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 30999
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
spec:
  replicas: 1
  strategy:
    type: Recreate
    
  selector:
    matchLabels:
      app: kibana
      release: "kibana"
  template:
    metadata:
      labels:
        app: kibana
        release: "kibana"
      annotations:
        
        configchecksum: 0111d49bd4ffba441269ecdfc98eee78f1c1a17eb71c1109ab346cb81c73ea4
    spec:
      securityContext:
        fsGroup: 1000
        
      volumes:
        - name: kibana-ssl
          secret:
            secretName: kibana-ssl
        - name: kibanaconfig
          configMap:
            name: kibana-kibana-config
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          
        image: "docker.elastic.co/kibana/kibana:7.3.0"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch-master:9200"
          - name: SERVER_HOST
            value: "0.0.0.0"
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    set -- -XGET -s --fail

                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                    fi

                    curl -k "$@" "http://localhost:5601${path}"
                }

                http "/app/kibana"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500m         
        volumeMounts:
          - name: kibana-ssl
            mountPath: /usr/share/kibana/config/certs
          - name: kibanaconfig
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
```

**Describe the bug:**

Kibana pod never start up successfully.

```
apiVersion: v1
data:
  kibana.yml: |
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/config/certs/kibana-kibana.key
    server.ssl.certificate: /usr/share/kibana/config/certs/kibana-kibana.crt
kind: ConfigMap
metadata:
  labels:
    app: kibana
    release: kibana
  name: kibana-kibana-config
  namespace: elk
```

**Steps to reproduce:**

1. enabled ssl to encrypt communication between browser and kibana
2. create .crt & .key, secret and added to kibana.yml
3. deploy kibana helm chart 7.3.0 

```
helm install --name kibana --namespace elk .
```

**Expected behavior:**
Use https to connect to kibana dashboard

**Provide logs and/or server output (if relevant):**

```
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["reporting","browser-driver","warning"],"pid":1,"message":"Enabling the Chromium sandbox provides an additional layer of protection."}
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["reporting","warning"],"pid":1,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["status","plugin:reporting@7.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["listening","info"],"pid":1,"message":"Server running at https://0.0.0.0:5601"}
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["info","http","server","Kibana"],"pid":1,"message":"http server running"}
{"type":"log","@timestamp":"2019-09-11T20:17:12Z","tags":["status","plugin:spaces@7.3.0","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"error","@timestamp":"2019-09-11T20:17:13Z","tags":["connection","client","error"],"pid":1,"level":"error","error":{"message":"140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n","name":"Error","stack":"Error: 140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"},"message":"140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"}
{"type":"error","@timestamp":"2019-09-11T20:17:23Z","tags":["connection","client","error"],"pid":1,"level":"error","error":{"message":"140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n","name":"Error","stack":"Error: 140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"},"message":"140586857269120:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"}
```

**Any additional context:**
