### ISSUE TITLE
Not able to configure action slack multiple account and link to specific webhook url (7.3.2)

### ISSUE THREAD

**Issue by dcvtruong** [elastic/helm-charts#311]
**Chart version:**
7.3.x, 7.4
**Kubernetes version:**
1.13.10
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kubespray
**Helm Version:**
2.12.1
**`helm get release` output**
N/A
e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
In 7.3.x configuring the slack webhook has to be create from the keystore command and not set from the elasticsearch.yml.  In elastic 7.4 docs, looks like configuring multiple slack account has to be from elasticsearch.yml

**Steps to reproduce:**

1. Refer to this URL where keystore is require to set the notification url, https://www.elastic.co/guide/en/elasticsearch/reference/7.4/actions-slack.html#configuring-slack
![Screen Shot 2019-10-02 at 2 05 31 PM](https://user-images.githubusercontent.com/45860078/66074070-fc3a4400-e51d-11e9-8ca1-d8e36901c06a.png)

2. multiple account from elastic docs,
![Screen Shot 2019-10-02 at 12 21 16 PM](https://user-images.githubusercontent.com/45860078/66067001-4e746880-e510-11e9-869f-f6eea02f5c05.png)

3. This can be set in elasticsearch.ml 6.x.  Not sure how it is in 7.3.x.
```
xpack.notification.slack:
  default_account: team1
  account:
    team1:
       url: https://hooks.slack.com/services/webhook1.../.....
       message_default:
           from: watcher
    team2:
       url: https://hooks.slack.com/services/webhook2.../.....
       message_default:
           from: watcher
```

**Expected behavior:**
Configure slack multiple account and link each account to slack specific webhook url

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by Crazybus** [comment]
Are you getting a specific error message or anything like that? It's not clear to me which part of this isn't working. 

>  In 7.3.x configuring the slack webhook has to be create from the keystore command and not set from the elasticsearch.yml. In elastic 7.4 docs, looks like configuring multiple slack account has to be from elasticsearch.yml

You configure the slack account in elasticsearch.yml with the exception of the `secure_url` which needs to be added to the keystore.

To add the secrets to the keystore you can do it like this:

```
kubectl create secret generic slack-team1 --from-literal=xpack.notification.slack.account.team1.secure_url='https://hooks.slack.com/services/asdasdasd/asdasdas/asdasd'
kubectl create secret generic slack-team2 --from-literal=xpack.notification.slack.account.team2.secure_url='https://hooks.slack.com/services/asdasdasd/asdasdas/asdasd'
```

And your values.yaml should look something like:

```
keystore:
  - secretName: slack-team1
  - secretName: slack-team2

esConfig:
  elasticsearch.yml: |
    xpack.notification.slack:
      default_account: team1
      account:
        team1:
          message_defaults:
            from: slack-team1
        team2:
          message_defaults:
            from: slack-team2
```

**Comment by dcvtruong** [comment]
@crazybus I try several different way and got the same error,
```
esConfig:
  elasticsearch.yml: |
    xpack:
      security:
        enabled: false
    xpack.notification.slack:
      default_account: devopswatcher
      account:
        devopswatcher:
          message_defaults:
            from: elastic-config-slack2
```
```
esConfig:
  elasticsearch.yml: |
    xpack:
      security:
        enabled: false
      notification.slack:
        default_account: devopswatcher
        account:
          devopswatcher:
            message_defaults:
              from: elastic-config-slack2
```
```
esConfig:
  elasticsearch.yml: |
    xpack:
      security:
        enabled: false
      notification:
        slack:
          default_account: devopswatcher
          account:
            devopswatcher:
              message_defaults:
                from: elastic-config-slack2
```

```
Error: UPGRADE FAILED: render error in "elasticsearch/templates/statefulset.yaml": template: elasticsearch/templates/statefulset.yaml:123:28: executing "elasticsearch/templates/statefulset.yaml" at <.secretName>: can't evaluate field secretName in type interface {}
```
