### ISSUE TITLE
disabling ilm through the helm-chart has no effect

### ISSUE THREAD

**Issue by acesir** [elastic/helm-charts#319]
**Chart version:** 7.1.1

**Kubernetes version:** 1.13

**Kubernetes provider:**  AWS EKS

**Helm Version:** 2.12.1

**`helm get release` output**

**Describe the bug:**

Attempting to disable metricbeat ilm settings does not seem to work.

**Steps to reproduce:**

Edit the default values.yaml and add:

```
metricbeatConfig:
  metricbeat.yml: |
    setup.ilm.enabled: false
    setup.ilm.overwrite: false
    setup.ilm.check_exists: false
```

**Expected behavior:**

Expected that ilm policies would not be created but they are regardless of disabling inside values.yaml. Also, disabling ilm using the non-helm deployment from here: https://raw.githubusercontent.com/elastic/beats/7.1/deploy/kubernetes/metricbeat-kubernetes.yaml seems to work just fine as we have previously been using that.

**Comment by Crazybus** [comment]
The issue is how you are specifying the fields. Your current configuration is overwriting `setup.ilm` everytime so the only one that will apply is `setup.ilm.check_exists: false`. 

From: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-namespacing.html

> Alternatively to using indentation, setting names can be used in collapsed form too.
> Note: having two settings with same fully collapsed path is invalid.

Your configuration should look like:
```
metricbeatConfig:
  metricbeat.yml: |
    setup.ilm:
      enabled: false
      overwrite: false
      check_exists: false
```

> Also, disabling ilm using the non-helm deployment from here: elastic/beats:deploy/kubernetes/metricbeat-kubernetes.yaml@7.1 (raw) seems to work just fine as we have previously been using that.

I don't see any reference to ILM in that configuration. It may have worked if you did it in a different order where you specified `setup.ilm.enabled: false` last.

**Comment by acesir** [comment]
Thanks for your response @Crazybus but even after making the changes you recommended the ilm is created regardless. What we had in the old deployment version was pretty much the same:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    setup.ilm.enabled: false
    setup.ilm.overwrite: true
    setup.ilm.check_exists: false
    setup.template.overwrite: true
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false
```

Not sure why the ilm is being created, i checked that it's correctly propagated in the pod as well as the config map and everything seems to be there but it does not seem to be enforced. Here is the values for the helm in the setup section:

```
---
# Allows you to add any config files in /usr/share/metricbeat
# such as metricbeat.yml
metricbeatConfig:
  metricbeat.yml: |
    setup.ilm:
      enabled: false
      overwrite: false
      check_exists: false
    system:
      hostfs: /hostfs
    metricbeat.modules:
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 30s
      host: "${NODE_NAME}"
      hosts: ["${NODE_NAME}:10255"]
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
    - module: kubernetes
      enabled: true
      metricsets:
        - event
    - module: system
      period: 30s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5
        by_memory: 5
    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
```

**Comment by Crazybus** [comment]
> helm get release output

Could you add the output of this? That way I can try to reproduce this myself. It should be something like `helm get metricbeat`  replacing metricbeat with your release name. 

Can you also add the log output from metricbeat on startup? 

> The issue is how you are specifying the fields. Your current configuration is overwriting setup.ilm everytime so the only one that will apply is setup.ilm.check_exists: false.

> From: elastic.co/guide/en/beats/libbeat/current/config-file-format-namespacing.html

I must have been getting confused, the original config does look valid and matches what is on https://www.elastic.co/guide/en/beats/metricbeat/current/ilm.html. So ignore this advice :P

**Comment by acesir** [comment]
@Crazybus both are attached bellow. I had to remove some hostname DNS names so if you see something not matching as far as hostnames go thats probably why.

[helm-metricbeat-out.txt](https://github.com/elastic/helm-charts/files/3729592/helm-metricbeat-out.txt)

[logs-from-metricbeat-in--metricbeat-kxpwt.txt](https://github.com/elastic/helm-charts/files/3729593/logs-from-metricbeat-in--metricbeat-kxpwt.txt)

**Comment by Crazybus** [comment]
I can't be sure since I don't have the logs for the kube-state-metrics metricbeat deployment. But I believe that it is the one responsible for creating the ILM policy.

```
metricbeatConfig:
  kube-state-metrics-metricbeat.yml: |
    metricbeat.modules:
    - module: kubernetes
      enabled: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
      period: 30s
      hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
    output.elasticsearch:
      hosts: ['http://elasticsearch-master.logging.svc.cluster.local:9200']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
  metricbeat.yml: |
    setup.ilm:
      enabled: false
      overwrite: false
      check_exists: false
    setup.template:
      overwrite: true
```

There is a metricbeat daemonset running (`metricbeat.yml`) and also the kube-state-metrics metricbeat deployment (`kube-state-metrics-metricbeat.yml`). Can you try added the ILM disabled stuff under `kube-state-metrics-metricbeat.yml` too and see if that works?
