### ISSUE TITLE
Adding new slack webhook to keystore post elasticsearch deployment

### ISSUE THREAD

**Issue by dcvtruong** [elastic/helm-charts#348]
**Chart version:**
7.4
**Kubernetes version:**
1.13.10
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kubespray
**Helm Version:**
2.12.1

**helm get release output:**

N/A

```
```

**Describe the bug:**
How to add new slack webhook to the keystore after elasticsearch has alreasy deployed?
**Steps to reproduce:**
N/A

**Expected behavior:**
N/A
**Provide logs and/or server output (if relevant):**
N/A
**Any additional context:**
N/A

**Comment by dcvtruong** [comment]
@jmlrt I believed this is an actual issue as there is not a way to add webhook to a current 7.4 ES.

**Comment by fatmcgav** [comment]
@dcvtruong Have you seen the docs around adding items into the Keystore? https://github.com/elastic/helm-charts/tree/master/elasticsearch#how-to-use-the-keystore

If you already have a running Elasticsearch deployment, it should just be a case of creating the required secrets in kubernetes, adding the appropriate config to a values override file, and running a `helm upgrade` against your deployment.

**Comment by dcvtruong** [comment]
@fatmcgav This is fine for a small environment and non-production.  Each time running helm upgrade to add a new slack webhook url to the keystore the ES pods required a restart of the pods and the setback is downtime.  For a large ES environment the restart of each pod will be hrs.  So it is not ideal to run the helm upgrade in a production environment.

**Comment by fatmcgav** [comment]
> Each time running helm upgrade to add a new slack webhook url to the keystore the ES pods required a restart of the pods and the setback is downtime.

Unfortunately that is an issue that is common across all methods of deploying Elasticsearch. If the keystore changes, elasticsearch needs to be restarted.

With regards to downtime, with a `helm upgrade`, there shouldn't be any downtime, as the pods will be restarted in a rolling fashion and only move onto the next pod when the last pod is reporting as healthy...

Is that not the behaviour you're seeing?

**Comment by jmlrt** [comment]
Hi @dcvtruong,

>With regards to downtime, with a helm upgrade, there shouldn't be any downtime, as the pods will be restarted in a rolling fashion and only move onto the next pod when the last pod is reporting as healthy...

👍 to @fatmcgav, unless you are running only one replica of elasticsearch which is really not recommended for production (and even for non-production in k8s world), there shouldn't be any downtime during helm upgrade.

This said, I'm not so much familiar with keystore feature, but the `keystore` init container is [here](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L147-L180). If you want to add new entry to the keystore outside of the helm-chart to avoid helm upgrade, you should be able to create a new temporary `keystore` pod based on this init container code.

Following [Reloadable secure settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html#reloadable-secure-settings) you could then call `POST _nodes/reload_secure_settings?pretty` using curl to your Elasticsearch cluster to ask your nodes re-reading the keystore (assuming your new keystore entry is a reloadable secure setting).

**Comment by dcvtruong** [comment]
@jmlrt I'm not sure I understand why creating a new keystore in addition to the keystore already running in the current ES and How is the slack action going to work in the new keystore? Is the alert notification will be routed from ES to the slack channel configure in the new keystore?

**Comment by jmlrt** [comment]
Keystore init container is just a container which is mounting the keystore volume used by Elasticsearch pod and the keystore k8s secret then use `elasticsearch-keystore create` command to create the keystore file inside the volume and `elasticsearch-keystore add-file` command to add secrets from keystore k8s secrets inside this keystore file.

Then Elasticsearch pod is mounting the same keystore volume and is able to use all the secrets added to the keystore by init container.

If you want to be able to add new secrets inside the keystore without running helm upgrade, I think that you can still add your slack configuration in a new `keystore-slack` k8s secret, then create a pod which will mount this secret and existing keystore volume then use `elasticsearch-keystore add-file` command to add this secret to the keystore, then you just need to request a reload of secure settings to your Elasticsearch cluster without any Helm change.

You would need this kind of pod template:
```
apiVersion: v1
kind: Pod
metadata:
  name: es-add-secret-to-keystore
spec:
  containers:
      - name: keystore
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.2"
        imagePullPolicy: "IfNotPresent"
        command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          set -euo pipefail
          cp -a /tmp/keystore /usr/share/elasticsearch/config/elasticsearch.keystore/
            echo "Adding file /tmp/keystoreSecrets/slack to keystore key xpack.notification.slack.account.monitoring.secure_url"
            elasticsearch-keystore add-file xpack.notification.slack.account.monitoring.secure_url /tmp/keystoreSecrets/slack
          cp -a /usr/share/elasticsearch/config/elasticsearch.keystore /tmp/keystore/
        volumeMounts:
          - name: keystore
            mountPath: /tmp/keystore
          - name: keystore-slack
            mountPath: /tmp/keystoreSecrets/slack
```

**Disclamer**: this is pure theory and hasn't been tested, using `helm upgrade` is the recommended way

**Side Note**: Helm Chart goals is to automate the deployment of Elasticsearch containers in Kubernetes with K8S production best practices, not to manage the whole lifecycle of an Elasticsearch cluster. You'll still need to administer you cluster outside of Helm Chart using custom pods or another way. If you prefer a more "battery included" experience I recommand you to take a look at https://github.com/elastic/cloud-on-k8s.
