### ISSUE TITLE
Cannot pull logstash chart

### ISSUE THREAD

**Issue by THPubs** [elastic/helm-charts#353]
I'm trying to include logstash in my helm chart. I added it to the requirements.yaml and tried to download it with the following command:

    helm dependency update

But i'm getting the following response:

```
Downloading elasticsearch from repo https://helm.elastic.co
Downloading metricbeat from repo https://helm.elastic.co
Downloading kibana from repo https://helm.elastic.co
Downloading filebeat from repo https://helm.elastic.co
Downloading logstash from repo https://helm.elastic.co
Save error occurred:  could not find : chart logstash not found in https://helm.elastic.co
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart logstash not found in https://helm.elastic.co
```

As you can see the other elastic stack components gets downloaded without issue. The problem is with logstash.

My requirements.yaml is as follows:

```
dependencies:
  - name: elasticsearch
    version: 7.4.x
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
    tags:
      - elasticsearch
  - name: metricbeat
    version: 7.4.x
    repository: https://helm.elastic.co
    condition: metricbeat.enabled
    tags:
      - metricbeat
  - name: kibana
    version: 7.4.x
    repository: https://helm.elastic.co
    condition: kibana.enabled
    tags:
      - kibana
  - name: filebeat
    version: 7.4.x
    repository: https://helm.elastic.co
    condition: filebeat.enabled
    tags:
      - filebeat
  - name: logstash
    version: 7.4.x
    repository: https://helm.elastic.co
    condition: logstash.enabled
    tags:
      - logstash
```

Any idea what's happening?
