### ISSUE TITLE
Filebeat chart not working

### ISSUE THREAD

**Issue by azelezni** [elastic/helm-charts#360]
**Chart version:**
filebeat-7.4.1

**Kubernetes version:**
v1.15.3

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
v1.15.3

**Helm Version:**
v2.15.1

**Helm get release:**
```
REVISION: 1
RELEASED: Sun Nov 10 09:30:31 2019
CHART: filebeat-7.4.1
USER-SUPPLIED VALUES:
annotations:
  filebeat_logs: "false"
filebeatConfig:
  filebeat.yml: |
    http.enabled: true
    logging.level: info
    monitoring.enabled: true
    monitoring.elasticsearch:
      hosts:
        - 51329cf25fcd4234a45cd9aa52a66d93.us-east-1.aws.found.io
      protocol: "https"
      username: "elastic"
      password: "8kxkkLJC63cB2pNeSWirubsy"

    processors:
      - add_cloud_metadata: {}
      - add_kubernetes_metadata:
          in_cluster: true
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when.or:
            - equals:
                kubernetes.annotations.filebeat_logs: "false"

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          labels.dedot: true
          annotations.dedot: true
          include_annotations:
            - filebeat_logs
            - log_format
            - workload_type
            - json_message_key
            - multiline_pattern
            - multiline_negate
            - multiline_match
          templates:
            - condition:
                equals:
                  kubernetes.annotations.log_format: json
              config:
                - type: docker
                  json.keys_under_root: true
                  json.overwrite_keys: true
                  json.message_key: "${kubernetes.annotations.json_message_key:message}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"

            - condition:
                equals:
                  kubernetes.annotations.log_format: multiline
              config:
                - type: docker
                  multiline.pattern: "${kubernetes.annotations.multiline_pattern:^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}}"
                  multiline.negate: "${kubernetes.annotations.multiline_negate:true}"
                  multiline.match: "${kubernetes.annotations.multiline_match:after}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"

            - condition:
                not.regexp:
                  kubernetes.annotations.log_format: "(json|multiline)"
              config:
                - type: docker
                  containers.ids:
                    - "${data.kubernetes.container.id}"

    output.redis:
      hosts:
        - redis-master
      key: fallback_list
      keys:
        - key: "%{[kubernetes.annotations.workload_type]}"
          mappings:
            application: "application_list"
            service: "service_list"
            system: "system_list"
image: docker.elastic.co/logstash/logstash
imagePullPolicy: IfNotPresent
imageTag: 7.4.2
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/controlplane
  operator: Equal
  value: "true"
- effect: NoExecute
  key: node-role.kubernetes.io/etcd
  operator: Equal
  value: "true"

COMPUTED VALUES:
affinity: {}
annotations:
  filebeat_logs: "false"
extraEnvs: []
extraVolumeMounts: ""
extraVolumes: ""
filebeatConfig:
  filebeat.yml: |
    http.enabled: true
    logging.level: info
    monitoring.enabled: true
    monitoring.elasticsearch:
      hosts:
        - 51329cf25fcd4234a45cd9aa52a66d93.us-east-1.aws.found.io
      protocol: "https"
      username: "elastic"
      password: "8kxkkLJC63cB2pNeSWirubsy"

    processors:
      - add_cloud_metadata: {}
      - add_kubernetes_metadata:
          in_cluster: true
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when.or:
            - equals:
                kubernetes.annotations.filebeat_logs: "false"

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          labels.dedot: true
          annotations.dedot: true
          include_annotations:
            - filebeat_logs
            - log_format
            - workload_type
            - json_message_key
            - multiline_pattern
            - multiline_negate
            - multiline_match
          templates:
            - condition:
                equals:
                  kubernetes.annotations.log_format: json
              config:
                - type: docker
                  json.keys_under_root: true
                  json.overwrite_keys: true
                  json.message_key: "${kubernetes.annotations.json_message_key:message}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"

            - condition:
                equals:
                  kubernetes.annotations.log_format: multiline
              config:
                - type: docker
                  multiline.pattern: "${kubernetes.annotations.multiline_pattern:^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}}"
                  multiline.negate: "${kubernetes.annotations.multiline_negate:true}"
                  multiline.match: "${kubernetes.annotations.multiline_match:after}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"

            - condition:
                not.regexp:
                  kubernetes.annotations.log_format: "(json|multiline)"
              config:
                - type: docker
                  containers.ids:
                    - "${data.kubernetes.container.id}"

    output.redis:
      hosts:
        - redis-master
      key: fallback_list
      keys:
        - key: "%{[kubernetes.annotations.workload_type]}"
          mappings:
            application: "application_list"
            service: "service_list"
            system: "system_list"
fullnameOverride: ""
hostPathRoot: /var/lib
image: docker.elastic.co/logstash/logstash
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.4.2
labels: {}
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
managedServiceAccount: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  privileged: false
  runAsUser: 0
priorityClassName: ""
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi
secretMounts: []
serviceAccount: ""
terminationGracePeriod: 30
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/controlplane
  operator: Equal
  value: "true"
- effect: NoExecute
  key: node-role.kubernetes.io/etcd
  operator: Equal
  value: "true"
updateStrategy: RollingUpdate

HOOKS:
MANIFEST:

---
# Source: filebeat/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-filebeat-config
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
data:
  filebeat.yml: |
    http.enabled: true
    logging.level: info
    monitoring.enabled: true
    monitoring.elasticsearch:
      hosts:
        - 51329cf25fcd4234a45cd9aa52a66d93.us-east-1.aws.found.io
      protocol: "https"
      username: "elastic"
      password: "8kxkkLJC63cB2pNeSWirubsy"
    
    processors:
      - add_cloud_metadata: {}
      - add_kubernetes_metadata:
          in_cluster: true
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when.or:
            - equals:
                kubernetes.annotations.filebeat_logs: "false"
    
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          labels.dedot: true
          annotations.dedot: true
          include_annotations:
            - filebeat_logs
            - log_format
            - workload_type
            - json_message_key
            - multiline_pattern
            - multiline_negate
            - multiline_match
          templates:
            - condition:
                equals:
                  kubernetes.annotations.log_format: json
              config:
                - type: docker
                  json.keys_under_root: true
                  json.overwrite_keys: true
                  json.message_key: "${kubernetes.annotations.json_message_key:message}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"
    
            - condition:
                equals:
                  kubernetes.annotations.log_format: multiline
              config:
                - type: docker
                  multiline.pattern: "${kubernetes.annotations.multiline_pattern:^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}}"
                  multiline.negate: "${kubernetes.annotations.multiline_negate:true}"
                  multiline.match: "${kubernetes.annotations.multiline_match:after}"
                  containers.ids:
                    - "${data.kubernetes.container.id}"
    
            - condition:
                not.regexp:
                  kubernetes.annotations.log_format: "(json|multiline)"
              config:
                - type: docker
                  containers.ids:
                    - "${data.kubernetes.container.id}"
    
    output.redis:
      hosts:
        - redis-master
      key: fallback_list
      keys:
        - key: "%{[kubernetes.annotations.workload_type]}"
          mappings:
            application: "application_list"
            service: "service_list"
            system: "system_list"
---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat-filebeat-cluster-role
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat-filebeat-cluster-role-binding
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
roleRef:
  kind: ClusterRole
  name: filebeat-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-filebeat
  namespace: elastic
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
spec:
  selector:
    matchLabels:
      app: "filebeat-filebeat"
      release: "filebeat"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        
        configChecksum: 1bef0ffbce11770ca0f0c8e02c481cab87d845b204a6c7ad5aee89578df12f6
      name: "filebeat-filebeat"
      labels:
        app: "filebeat-filebeat"
        chart: "filebeat-7.4.1"
        heritage: "Tiller"
        release: "filebeat"
    spec:
      tolerations: 
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        operator: Equal
        value: "true"
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Equal
        value: "true"
      
      serviceAccountName: filebeat-filebeat
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-filebeat-config
      - name: data
        hostPath:
          path: /var/lib/filebeat-filebeat-elastic-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: "filebeat"
        image: "docker.elastic.co/logstash/logstash:7.4.2"
        imagePullPolicy: "IfNotPresent"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
          
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false
          runAsUser: 0
          
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # Necessary when using autodiscovery; avoid mounting it otherwise
        # See: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true
```

**Describe the bug:**
`Readiness probe failed: sh: line 1: filebeat: command not found`

**Steps to reproduce:**
1. Install the chart

**Comment by jmlrt** [comment]
Hi @azelezni,

I obfuscated ES host and password in the output of your Helm release:
```
    monitoring.elasticsearch:
      hosts:
        - XXX.us-east-1.aws.found.io
      protocol: "https"
      username: "elastic"
      password: "XXXX"
```

I hope the values weren't real one, if that's the case, I highly encourage you to change your password because this has been public for 3 days before I saw it.
