### ISSUE TITLE
[filebeat|elasticsearch] Labels not propagated to pods

### ISSUE THREAD

**Issue by chicken231** [elastic/helm-charts#384]
**Chart version:** 7.4.1

**Kubernetes version:** 1.14

**Kubernetes provider:** AWS EKS

**Helm Version:** 2.15.2

**`helm get release` output**

```yaml
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.4.1"
    heritage: "Tiller"
    release: "filebeat"
    app.kubernetes.io/name: "filebeat"
spec:
  selector:
    matchLabels:
      app: "filebeat-filebeat"
      release: "filebeat"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        
        configChecksum: 63c911247bda6752c8d4a661a974be82c68ce8bc7d1fc4797fdf8cfffa7ea67
      name: "filebeat-filebeat"
      labels:
        app: "filebeat-filebeat"
        chart: "filebeat-7.4.1"
        heritage: "Tiller"
        release: "filebeat"
    spec:
      serviceAccountName: filebeat-filebeat
      terminationGracePeriodSeconds: 60
      volumes:
      - name: elasticsearch-es-certificates-pem
        secret:
          secretName: elasticsearch-es-certificates-pem
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-filebeat-config
      - name: data
        hostPath:
          path: /var/lib/filebeat-filebeat-monitoring-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: "filebeat"
        image: "docker.elastic.co/beats/filebeat:7.4.1"
        imagePullPolicy: "IfNotPresent"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          
        resources:
          limits:
            cpu: 200m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH_USERNAME
              name: elasticsearch-filebeat-credentials
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH_PASSWORD
              name: elasticsearch-filebeat-credentials
        
        securityContext:
          privileged: false
          runAsUser: 0
          
        volumeMounts:
        - name: elasticsearch-es-certificates-pem
          mountPath: /usr/share/filebeat/certs
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # Necessary when using autodiscovery; avoid mounting it otherwise
        # See: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true

```

**Describe the bug:** For `labels`, the README says:
> Configurable label applied to all Filebeat pods

However, labels are not applied to `Pods`. They're only applied to the `DaemonSet` object at `metadata.labels` (`values.yaml`). See: https://github.com/elastic/helm-charts/blob/7.4.1/filebeat/templates/daemonset.yaml#L11
They should also be applied at `spec.template.labels`.

This appears to be a bug with the elasticsearch chart as well.

**Steps to reproduce:**

1. Define a label in values.yaml. Key = `labels`. Example label: `app.kubernetes.io/name: "filebeat"`
2. Helm upgrade.

**Expected behavior:** Labels applied to pods

**Provide logs and/or server output (if relevant):**

**Any additional context:**
