### ISSUE TITLE
[elasticsearch] recommended method to automate an api call (e.g. ILM) post deployment?

### ISSUE THREAD

**Issue by naseemkullah** [elastic/helm-charts#440]
This is helm related so I am not asking in the ES forum.

I would like to automate the following api call:

```
PUT _template/my_template
{
  "index_patterns": [
    "logstash-*"
  ],
  "settings": {
    "number_of_shards": 8,
    "number_of_replicas": 1
  }
}
```

I am trying with these values in the helm chart, essentially the idea is to wait until the ES cluster has started (relies heavily on health check mechanism that creates the "start file")... is this a recommended approach?

```
lifecycle:
  postStart:
    exec:
      command:
        - sh
        - -c
        - |
          #!/bin/sh
          # Add a template to adjust number of shards/replicas
          TEMPLATE_NAME=my_template
          START_FILE=/tmp/.es_start_file
          INDEX_PATTERN="logstash-*"
          SHARD_COUNT=8
          REPLICA_COUNT=1
          while [ ! -f ${START_FILE} ]; do
            sleep 1
          done
          curl -XPUT "http://localhost:9200/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'{"index_patterns":['"$INDEX_PATTERN"'],"settings":{"number_of_shards":'$SHARD_COUNT',"number_of_replicas":'$REPLICA_COUNT'}}'
```

FWIW have not gotten it to work yet, pod remains in Initialization phase:
```
elasticsearch-master-2                   0/1     PodInitializing   0          12m8s
```

But let me know if I am on the right track please.

cc @jmlrt  @Crazybus  would love to get your input.

**Comment by Crazybus** [comment]
Logstash has a native way to manage installing and configuring templates as part of the Elasticsearch output plugin. Have you already given this a try?  https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-template

As for why your current method isn't working. To help debug I would recommend running the script from directly within the Logstash container to see what the error is. The first thing that stands out is that you are trying to connect http://localhost:9200. This is going to try to connect to the Logstash container on port 9200 which probably isn't right. Instead it should be http://elasticsearch-master:9200.

**Comment by naseemkullah** [comment]
Thanks @crazybus, while the index pattern is logstash-* we aren't actually using log stash, which is confusing sorry. We use fluent bit as the log forwarder which lacks this template configuration capability and is probably where the problem should be solved.

That aside, is it possible to run a logstash job post deployment of the release?

**Comment by naseemkullah** [comment]
https://github.com/fluent/fluent-bit/issues/1872 created by the way

**Comment by pbecotte** [comment]
https://helm.sh/docs/topics/charts_hooks/ 

Helm hooks are the best way to do this IMO, but these helm charts dont have any extension point built in for it. 

Logstash or not, `localhost` is the wrong hostname for your script. That should be the url of your elasticsearch master instance- if you're using these charts, `elasticsearch-master`

**Comment by naseemkullah** [comment]
It's set to `localhost` because its a post start lifecycle hook on the elasticsearch-master deployment, regardless it does not seem to work properly

**Comment by naseemkullah** [comment]
I like the idea of removing the dependency on that file, so I've tried:

```yaml
lifecycle:
  postStart:
    exec:
      command:
        - sh
        - -c
        - |
          #!/bin/bash
          # Add a template to adjust number of shards/replicas
          TEMPLATE_NAME=my_template2
          INDEX_PATTERN="logstash2-*"
          SHARD_COUNT=8
          REPLICA_COUNT=1
          ES_URL=http://localhost:9200
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
          curl -XPUT "$ES_URL/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'{"index_patterns":['"$INDEX_PATTERN"'],"settings":{"number_of_shards":'$SHARD_COUNT',"number_of_replicas":'$REPLICA_COUNT'}}'
```

However that did not seem to create the expected template (though the pods did start).
