### ISSUE TITLE
elastic/metricbeat:7.5.1 deployment readinessProbe broken

### ISSUE THREAD

**Issue by mmisztal1980** [elastic/helm-charts#441]
I've attempted to install the `elastic/metricbeat:7.5.1` from the registry. Upon installation I've noticed that my deployment was failing roll out. The reason turned out to be a dually generated `exec` node of the readinessProbe in the deployment:

```yaml
readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              metricbeat test output
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              metricbeat test output
```

I've run `helm fetch elastic/metricbeat` and verified that the issue is indeed present in the released chart, the content indeicates that the values.yaml yaml is being appended to an existing `exec` node:

<img width="1680" alt="Screenshot 2020-01-10 at 17 42 02" src="https://user-images.githubusercontent.com/1357057/72170463-3181e800-33d1-11ea-9a2b-5ea55a34bbd6.png">

@jmlrt you guys aware of this?
