### ISSUE TITLE
Kibana health check fails when Auth is enabled because readiness probe 302's to login

### ISSUE THREAD

**Issue by justinturpin** [elastic/helm-charts#442]
**Chart version:**

7.5.1

**Kubernetes version:**

1.13.1-eks

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

EKS

**Helm Version:**

2.14.3

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**

Kibana never becomes healthy when Auth is enabled (by setting ELASTICSEARCH_USERNAME and ELASTICSEARCH_PASSWORD environment variables). The readiness probe includes:

```
              STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
              if [[ "${STATUS}" -eq 200 ]]; then
                exit 0
              fi
```

However this does not 200, but instead 302's to /login:

```
bash-4.2$ curl http://localhost:5601/app/kibana -vvv
* About to connect() to localhost port 5601 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5601 (#0)
> GET /app/kibana HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5601
> Accept: */*
> 
< HTTP/1.1 302 Found
< location: /login?next=%2Fapp%2Fkibana
< cache-control: no-cache
< content-length: 0
< Date: Fri, 10 Jan 2020 20:34:29 GMT
< Connection: keep-alive
```

This is confirmed with logs:

```
{"type":"response","@timestamp":"2020-01-10T20:39:43Z","tags":[],"pid":8,"method":"get","statusCode":302,"req":{"url":"/app/kibana","method":"get","headers":{"user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":24,"contentLength":9},"message":"GET /app/kibana 302 24ms - 9.0B"}
```

**Any additional context:**

It might be sufficient to just have a health check that instead of checks for an explicit 200, makes sure its less than a 400 or 500.

**Comment by SergK** [comment]
Hi @justinturpin , this PR https://github.com/elastic/helm-charts/pull/405 should resolve your issue

**Comment by pbecotte** [comment]
This is actually the correct behavior. If security is enabled, Kibana does a 302 to the https port. You can get this to pass by switching `protocol` to `https`.

I have included my currently running values.yaml-

```
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/tls-acme: "true"
    path: "/"
    hosts:
      - kibana2.mydomain.com
    tls:
      - hosts:
          - kibana2.mydomain.com
        secretName: kibana-tls-secret

  elasticsearchHosts: "https://elasticsearch-master:9200"

  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: password
    - name: 'KIBANA_ENCRYPTION_KEY'
      valueFrom:
        secretKeyRef:
          name: kibana
          key: encryptionkey

  kibanaConfig:
    kibana.yml: |
      server.ssl:
        enabled: true
        key: /usr/share/kibana/config/certs/kibana.key
        certificate: /usr/share/kibana/config/certs/kibana.pem
      xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
      elasticsearch.ssl:
        certificateAuthorities: /usr/share/kibana/config/certs/elastic-ca.pem
  protocol: https

  secretMounts:
    - name: elastic-certificate-pem
      secretName: kibana-certs
      path: /usr/share/kibana/config/certs
```

**Comment by justinturpin** [comment]
I see, I was about to say we don't terminate TLS on the pod since we use cert-manager, but I see you've mounted in the secret. That makes sense. Thanks!

**Comment by SergK** [comment]
In my case the issue is still valid, since I'm installing this plugin https://github.com/novomatic-tech/keycloak-kibana

**Comment by pbecotte** [comment]
According to the readme for that plugin, it requires auth to be disabled., which... would make this not apply?

**Comment by SergK** [comment]
Yes, in my case:
`xpack.security.enabled: false`


and here is the result from pod:

```
bash-4.2$ curl -I http://localhost:5601/app/kibana
HTTP/1.1 302 Found
location: https://keycloak.xxxxx.xxxxx.com/auth/realms/cicd/protocol/openid-connect/auth?client_id=kibana&state=xxxxxxxxxxxxxxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A5601%2Fsso%2Flogin%3Fauth_callback%3D1&scope=openid&response_type=code
kbn-name: kibana
kbn-xpack-sig: zzzzzzzzzzzzzzzzzzzzzzzzzz
cache-control: no-cache
content-length: 0
Date: Wed, 15 Jan 2020 12:51:39 GMT
Connection: keep-alive
```

**Comment by pbecotte** [comment]
well okay then, that is a completely different url :) seems like this does need to be configurable.

**Comment by jgato** [comment]
I think I have a similar problem... it is not working my connection between Kibana and ES. It seems Kibana is not using the user I have created in ES. Even if this is pointed:

```

extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1800"

  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey


secretMounts:
  - name: elastic-certificates
    secretName: elk-certificates-pem
    path: /usr/share/kibana/config/certs

kibanaConfig: 
  kibana.yml: |
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs/elk-ca.pem
      certificate: /usr/share/kibana/config/certs/elk-ca.pem
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/elk-ca.pem
      verificationMode: certificate
    elasticsearch.username: ${ELASTICSEARCH_USERNAME}
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

```

The kibana logs:

```
{"type":"log","@timestamp":"2020-04-20T10:58:18Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
```
It is pretty strange, it seems it is using user admin. But the username in the ENV variable is other different.  If I configure the yaml, with user/password (no secretes) just in clear, the log is still sayin that admin error. Even if I have configured another name for the user.

Please, any help?
