### ISSUE TITLE
[metricbeat] Different tolerations, nodeSelector and affinity for deployment and daemonset

### ISSUE THREAD

**Issue by FedeBev** [elastic/helm-charts#446]
**Describe the feature:**
In my opinion would be great to have a different value option for tolerations, nodeSelector and affinity of daemonset and deployment.

An example of value.yaml could be the following:
```yaml
daemonset:
  nodeSelector: {}

  tolerations:
    - operator: "Exists"

deployment:
  nodeSelector:
    my_key: "true"

  tolerations:
    - key: my_key
      value: "true"
      operator: Equal
      effect: NoExecute
```

**Describe a specific use case for the feature:**

In our case, for example, we have a node pool dedicated to elastic stack and we would like to keep all the pods on it, when possible. This is for billing reason and to prevent the infrastructure components load from disturbing customer applications

If PR are welcome I can deal with that
