### ISSUE TITLE
[Elasticsearch] issue with max file descriptors

### ISSUE THREAD

**Issue by dmytrokohut** [elastic/helm-charts#486]
**Chart version:** 7.5.2

**Kubernetes version:** 1.12.10

**Kubernetes provider:** AWS (Amazon Web Services)

**Helm Version:** 3.0.0


Hi,
I have been trying to launch Elasticsearch using Helm-chart but I faced an issue with Elasticsearch:
```
 ERROR: [1] bootstrap checks failed                                                                                                                                                                                                                                           
 [1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65535] 
```

Here is entire `values.yml` file content:
```
---
clusterName: "elasticsearch"
nodeGroup: "master"

masterService: ""

roles:
  master: "true"
  ingest: "true"
  data: "true"

replicas: 5
minimumMasterNodes: 3

esMajorVersion: ""

esConfig:
  elasticsearch.yml: |
    xpack:
      monitoring:
        collection:
          enabled: true

extraEnvs: []

secretMounts: []

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.5.2"
imagePullPolicy: "IfNotPresent"

podAnnotations: {}

labels: {}

esJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

initResources: {}

sidecarResources: {}

networkHost: "0.0.0.0"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Gi

rbac:
  create: false
  serviceAccountName: ""

podSecurityPolicy:
  create: false
  name: ""
  spec:
    privileged: true
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
      - secret
      - configMap
      - persistentVolumeClaim

persistence:
  enabled: true
  annotations: {}

extraVolumes: ""

extraVolumeMounts: ""

extraInitContainers: ""

priorityClassName: ""

antiAffinityTopologyKey: "kubernetes.io/hostname"

antiAffinity: "hard"

nodeAffinity: {}

podManagementPolicy: "Parallel"

protocol: http
httpPort: 9200
transportPort: 9300

service:
  labels: {}
  labelsHeadless: {}
  type: ClusterIP
  nodePort: ""
  annotations: {}
  httpPortName: http
  transportPortName: transport

updateStrategy: RollingUpdate

maxUnavailable: 1

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

fsGroup: ""

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

terminationGracePeriod: 120

sysctlVmMaxMapCount: 262144

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

clusterHealthCheckParams: "wait_for_status=green&timeout=1s"

schedulerName: ""

imagePullSecrets: []
nodeSelector: {}
tolerations: []

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

nameOverride: ""
fullnameOverride: ""

masterTerminationFix: false

lifecycle: {}

sysctlInitContainer:
  enabled: true

keystore: []
```

**Steps to reproduce:**

1. Copy content displayed above to a local `values.yaml` file
2. Run command `helm install elastic/elasticsearch --generate-name --namespace <k8s-namespace> -f ./values.yaml`

**Expected behavior:**
Successfully launched Elasticsearch cluster.

**Actual behavior:**
Every _K8S_ pod successfully passing the initialization step (`configure-sysctl` container), but an exception happens when Elasticsearch is trying to launch.

**Entire log of single Elasticsearch instance:**
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"type": "server", "timestamp": "2020-02-14T14:37:03,154Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/nvme4n1)]], net usable_space [98.2gb], net total_space [98.3gb], types [ext4]" }
{"type": "server", "timestamp": "2020-02-14T14:37:03,158Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "heap size [1015.6mb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2020-02-14T14:37:03,161Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "node name [elasticsearch-master-1], node ID [mrEBdeU9Td-KnFQpXWkm9Q], cluster name [elasticsearch]" }
{"type": "server", "timestamp": "2020-02-14T14:37:03,161Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "version[7.5.2], pid[1], build[default/docker/8bec50e1e0ad29dad5653712cf3bb580cd1afcdf/2020-01-15T12:11:52.313576Z], OS[Linux/4.14.97-90.72.amzn2.x86_64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]" }
{"type": "server", "timestamp": "2020-02-14T14:37:03,162Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
{"type": "server", "timestamp": "2020-02-14T14:37:03,162Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-5903878101634558292, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xmx1g, -Xms1g, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,662Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [aggs-matrix-stats]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,662Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [analysis-common]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [flattened]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [frozen-indices]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [ingest-common]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [ingest-geoip]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [ingest-user-agent]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [lang-expression]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [lang-mustache]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [lang-painless]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [mapper-extras]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,665Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [parent-join]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,665Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [percolator]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,665Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [rank-eval]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,665Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [reindex]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,666Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [repository-url]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,666Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [search-business-rules]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,666Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [spatial]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,666Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [transform]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,666Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [transport-netty4]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,667Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [vectors]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,667Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-analytics]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,667Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-ccr]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,667Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-core]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-deprecation]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-enrich]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-graph]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-ilm]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-logstash]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,669Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-ml]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,669Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-monitoring]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,669Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-rollup]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,670Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-security]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,670Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-sql]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,670Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-voting-only-node]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,670Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2020-02-14T14:37:07,671Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2020-02-14T14:37:16,038Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
{"type": "server", "timestamp": "2020-02-14T14:37:17,044Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "[controller/89] [Main.cc@110] controller (64 bit): Version 7.5.2 (Build 68f6981dfb8e2d) Copyright (c) 2020 Elasticsearch BV" }
{"type": "server", "timestamp": "2020-02-14T14:37:18,160Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" }
{"type": "server", "timestamp": "2020-02-14T14:37:18,435Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "using discovery type [zen] and seed hosts providers [settings]" }
{"type": "server", "timestamp": "2020-02-14T14:37:20,270Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "initialized" }
{"type": "server", "timestamp": "2020-02-14T14:37:20,270Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "starting ..." }
{"type": "server", "timestamp": "2020-02-14T14:37:20,567Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "publish_address {172.16.80.101:9300}, bound_addresses {0.0.0.0:9300}" }
{"type": "server", "timestamp": "2020-02-14T14:37:20,844Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }
ERROR: [1] bootstrap checks failed
[1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65535]
{"type": "server", "timestamp": "2020-02-14T14:37:20,854Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "stopping ..." }
{"type": "server", "timestamp": "2020-02-14T14:37:20,870Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "stopped" }
{"type": "server", "timestamp": "2020-02-14T14:37:20,871Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "closing ..." }
{"type": "server", "timestamp": "2020-02-14T14:37:20,934Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "closed" }
{"type": "server", "timestamp": "2020-02-14T14:37:20,936Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "Native controller process has stopped - no new native processes can be started" }
```

**Worth to mention:**
I have been trying to launch the Elasticsearch with the same configuration as above on another _K8S_ cluster and it works well there. The issue happens only on this cluster and I don't have a clue why this happens.
