### ISSUE TITLE
[apm-server] liveness & readiness probe values are not valid

### ISSUE THREAD

**Issue by acarsercan** [elastic/helm-charts#488]
Hi,

values.yaml allows you to set liveness & readiness probes, yet deployment.yaml does not pass the same values

templates/deployment.yaml
```
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 600
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 600
```
Regards
