### ISSUE TITLE
[filebeat] Impossible to downgrade filebeat version

### ISSUE THREAD

**Issue by dudicoco** [elastic/helm-charts#489]
We had filebeat v7.5.1 installed on a k8s cluster, when attempting to downgrade to v6.4.2 the following error appeared in the logs:
```Registry file path must be a file. /usr/share/filebeat/data/registry is a directory```

It seems that the directory structure is different between the two versions, making it not possible to downgrade to the older version.
We had to replace the nodes in order to get around this issue.

**Comment by jmlrt** [comment]
Hi @dudicoco,
Thank for reporting this issue.
Downgrade between 2 different major versions isn't supported.
Moreover, this downgrade issue isn't specific to Helm charts.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.

**Comment by NickLavrov** [comment]
In case anyone finds their way here, I solved this by first uninstalling filebeat so that no pods would be trying to access that path, then deploying a daemonset of nginx pods to all nodes (as filebeat was deployed to all nodes) with storage configured to match that filepath:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testing
spec:
  selector:
    matchLabels:
      name: my-daemonset-container 
  template:
    metadata:
      labels:
        name: my-daemonset-container
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/
          name: data
      volumes:
      - hostPath:
          path: /var/lib/
          type: DirectoryOrCreate
        name: data
```

Then you can exec into each one and remove the folder (you can script it if it's a huge number of nodes):

`kubectl exec -it testing-ttxqb -- rm -rf /usr/share/filebeat-release-filebeat-elk-data` (that pod name is an example)

Note that I got the name `filebeat-release-filebeat-elk-data` from `kubectl get ds filebeat-release-filebeat -o yaml` (that's my helm release) and looking at volumes and volumeMounts section.

After removing this, I was able to create the filebeat v6 release.
