### ISSUE TITLE
multi volumeClaimTemplate support on elasticsearch chart

### ISSUE THREAD

**Issue by batrako** [elastic/helm-charts#49]
With elasticsearch , in some cases , we need some extra volumes  with your own properties  to  store snapshots or backups (for example). Current version , only supports one VolumeClaimTemplate.  Could be  very useful for us, support for multi volumes on elasticsearch group nodes.
Thanks

**Comment by Crazybus** [comment]
The repository used for taking snapshots needs to be a [shared file system](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository).

> In order to register the shared file system repository it is necessary to mount the same shared filesystem to the same location on all master and data nodes. 

Adding the ability to allow multiple `volumeClaimTemplates` wouldn't work for a snapshot repository. As it would create a separate persistent volume claim for each node. 

Instead it sounds like we need to add the ability to mount extra volumes. This would only work for storage that supports [ReadWriteMany](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes). Another alternative is to use one of the [repository plugins](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_repository_plugins) if one of those backends is available to you. 

This is what would need to be added to make this work:

1. Ability to define extra [persistentVolumeClaims](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims).
2. Ability to mount [persistent volume claims](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes) as volumes. 

The configuration would look something like this:

```
persistentVolumesClaims:
  claimName:
    accessModes:
      - ReadWriteMany
    volumeMode: Filesystem
    resources:
      requests:
        storage: 8Gi
    storageClassName: slow
    selector:
      matchLabels:
        release: "stable"

persistentVolumeMounts:
  claimName: /usr/share/elasticsearch/snapshots
```
