### ISSUE TITLE
Setup cluster with xpack enabled. 

### ISSUE THREAD

**Issue by SCLogo** [elastic/helm-charts#506]
Hello all,

I would like to run elasticsearch cluster in kubernetes with isito installed and mtls forced over envoy proxy.

Cluster is running, but if I did not set any security, the cluster members never go to ready  state.
If I enable security, then cluster restarting all time 

my values.yaml

```

elasticsearch:
  clusterName: elasticsearch
  replicas: 2
  volumeClaimTemplate:
    resources:
      requests:
        storage: 8Gi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ALL]
  protocol: https
  roles:
    master: "true"
    ingest: "true"
    data: "true"
  #extraEnvs:
  #  - name: ELASTIC_PASSWORD
  #    valueFrom:
  #      secretKeyRef:
  #        name: elasticsearch-secret
  #        key: password
  #  - name: ELASTIC_USERNAME
  #    valueFrom:
  #      secretKeyRef:
  #        name: elasticsearch-secret
  #        key: username

#  keystore:
#    - secretName: elasticsearch-secret
  #esConfig:
  #  elasticsearch.yml: |
  #    xpack.security.enabled: true
  #    xpack.security.transport.ssl.enabled: true
  #    xpack.security.transport.ssl.verification_mode: certificate
  #    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
  #    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
  #    xpack.security.http.ssl.enabled: true
  #    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
  #    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
  secretMounts:
    - name: elastic-certificates
      secretName: elastic-certificates
      path: /usr/share/elasticsearch/config/certs
 
```
