### ISSUE TITLE
Single helm chart for full cluster deployment?

### ISSUE THREAD

**Issue by AXington** [elastic/helm-charts#510]
Please let me know if I'm missing something here, but it seems like a single helm chart that installed all the different components would be good. You could do it by having a master chart that had the others as sub charts. This is fairly common, example:

https://github.com/helm/charts/blob/master/stable/prometheus-operator/requirements.yaml

Further, it seems like for ElasticSearch you'd have to have multiple of the same chart installed in order to have separate Masters, Data, and Ingest nodes. That's both really inconvenient and kind of antithetical to typical helm methods. You should be able to just set some flags in the values.yaml like:
```yaml
masters:
  roles:
    data: false
    ingest: false

dedicatedData:
  enabled: true
dedicatedIngest:
  enabled: true
```
