### ISSUE TITLE
[Elasticsearch] Allow to customize antiAffinity 

### ISSUE THREAD

**Issue by cambierr** [elastic/helm-charts#526]
**Describe the feature:**
I'm in a multi AZ deployment of this chart and I'd like to be able to deploy it with custom antiAffinity:
- set a `preferredDuringSchedulingIgnoredDuringExecution` based on the AZ topologyKey
- set a `requiredDuringSchedulingIgnoredDuringExecution` based on the hostname topologyKey

**Describe a specific use case for the feature:**
Multi AZ deployments where you want to make sure you don't have two pods on the same node, and at the same time you want to distribute as much as possible on your AZs.

**Suggestion:**
Allow to set a custom value to `antiAffinity` and use it as `else` clause in:
```yaml
      {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # ...
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # ...
      {{- else }}
        podAntiAffinity:
          {{- .Values.antiAffinity }}
      {{- end }}
```
