### ISSUE TITLE
RFC: change extraEnvs to be a map instead of a list.

### ISSUE THREAD

**Issue by jordansissel** [elastic/helm-charts#53]
When using nested charts (parent/child/etc), it's often useful to add additional entries for values to pass into in child charts. However, `extraEnvs` is a list, and [helm cannot merge lists](https://github.com/helm/helm/issues/3767), but it can merge maps! (Citation: https://github.com/jordansissel/experiments/tree/master/helm/subchart-values-from-parent)

By way of example, I might have one child chart which configures Elasticsearch with my favorite default features (enable security, enable tls, etc). And I could create a new chart where I want this, plus creating a SAML realm. Because `extraEnvs` is a list, I can't just inject these SAML-specific settings. Instead, I have to copy+paste the child chart's `extraEnvs` (enable security, enable tls, etc) and append my SAML ones.

If `extraEnvs` were a map, I believe this would be solved:

Example appearance in the child described in above:
```
extraEnvs:
  xpack.security.enabled: { value: true }
  ...
  ELASTIC_PASSWORD: 
    valueFrom: { secretKeyRef: { name: elastic-credentials, key: password } }
```

And the parent chart (to add SAML, for example)
```
extraEnvs:
  xpack.security.authc.realms.saml1.type: { value: true }
  ...
```

Thoughts? I know this would deviate from Kubernetes "environment variables are defined as an list", so I'm open to discussion.

## Alternative approach

Stepping back, one alternative could be to have a general "settings" which could be used to generate a configmap instead of using environment variables for settings.
