### ISSUE TITLE
[APM-SERVER] doesn't deploy on k8s 1.17.0 with HorizontalPodAutoscaler enabled

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/helm-charts#531]
**Chart version:**
7.6.1

**Kubernetes version:**
1.17.0

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kind

**Helm Version:**
3.0.2

**`helm get values apm` output**

```
replicas: 1
autoscaling:
  enabled: true
image: "elastic/apm-server"
imageTag: "7.6.1"
imagePullPolicy: "Always"
imagePullSecrets:
  - name: docker.elastic.co
resources:
  requests:
    memory: "0.2Gi"
    cpu: 0.1
  limits:
    cpu: 0.8
    memory: "0.7Gi"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  path: /
  hosts:
    - apm.IP.ip.es.io
  tls:
    - hosts:
      - apm.IP.ip.es.io
      secretName: apm-ingress-tls
extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: es-creds
        key: user
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: es-creds
        key: password
  - name: ELASTICSEARCH_PROTO
    valueFrom:
      secretKeyRef:
        name: es-creds
        key: protocol
  - name: ELASTICSEARCH_HOST
    valueFrom:
      secretKeyRef:
        name: es-creds
        key: host
  - name: ELASTICSEARCH_PORT
    valueFrom:
      secretKeyRef:
        name: es-creds
        key: port
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: KIBANA_HOST
    valueFrom:
      secretKeyRef:
        name: kibana-creds
        key: host
  - name: KIBANA_PROTO
    valueFrom:
      secretKeyRef:
        name: kibana-creds
        key: protocol
  - name: KIBANA_PORT
    valueFrom:
      secretKeyRef:
        name: kibana-creds
        key: port
  - name: KIBANA_USERNAME
    valueFrom:
      secretKeyRef:
        name: kibana-creds
        key: user
  - name: KIBANA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kibana-creds
        key: password
  - name: APM_TOKEN
    valueFrom:
      secretKeyRef:
        name: apm-creds
        key: token
extraVolumes:
- name: default-tls
  secret:
    defaultMode: 420
    secretName: default-tls
extraVolumeMounts:
  - mountPath: "/usr/share/apm-server/config/certs"
    name: default-tls
service:
  type: ClusterIP
  port: "8200"
  targetPort: "8200"
  annotations: {}
apmConfig:
  apm-server.yml: |
    logging.level: info
    apm-server:
      host: "0.0.0.0:8200"
      rum.enabled: true
      ilm.enabled: true
      secret_token: ${APM_TOKEN}
    # disable due causes APM Server does not start
      ssl.enabled: false
      ssl.key: /usr/share/apm-server/config/certs/tls.key
      ssl.certificate: /usr/share/apm-server/config/certs/tls.crt
    queue: {}
    monitoring.elasticsearch.ssl.verification_mode: none
    setup.kibana:
      host: ${KIBANA_PROTO}://${KIBANA_HOST}:${KIBANA_PORT}
      protocol: ${KIBANA_PROTO}
      username: ${KIBANA_USERNAME}
      password: ${KIBANA_PASSWORD}
    output.elasticsearch:
      enabled: true
      hosts: ["${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.verification_mode: none

```

**Describe the bug:**

The helm chart doesn't deploy on k8s 1.17.0 with HorizontalPodAutoscaler enabled.

**Steps to reproduce:**

1. Install the Helm chart with the provider configuration
2. it fails to deploy

**Expected behavior:**

The Helm chart should be installed and run with HorizontalPodAutoscaler enabled.

**Provide logs and/or server output (if relevant):**

```
'Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "networking.k8s.io/v1beta1"'
```

Supported autoscaler apiVersions

```
$>kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
```
