### ISSUE TITLE
[Kibana] readinessProbe does not support redirection (302)

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/helm-charts#548]
**Chart version:**
7.6.1

**Kubernetes version:**
1.14

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
GKE

**Helm Version:**
3.0.2

**`helm get release` output**

```
NAME: kibana
LAST DEPLOYED: Mon Mar 30 11:32:37 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
elasticsearchHosts: https://es.example.com:9243
extraEnvs:
- name: ELASTICSEARCH_USERNAME
  valueFrom:
    secretKeyRef:
      key: user
      name: es-creds
- name: ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: es-creds
- name: SERVER_HOST
  value: 0.0.0.0
healthCheckPath: /login
httpPort: 5601
image: elastic/kibana
imagePullPolicy: Always
imageTag: 8.0.0-SNAPSHOT
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  enabled: true
  hosts:
  - kibana.example.com
  path: /
  tls:
  - hosts:
    - kibana.example.com
    secretName: kibana-ingress-tls
kibanaConfig:
  kibana.yml: |
    kibana.disableWelcomeScreen: true
    telemetry.banner: false
    logging.quiet: true
    kibana.index: .kibana_k8s
    xpack.task_manager.index: .kibana_task_manager_k8s
    xpack.security.authc.providers: [basic]
    xpack.monitoring.enabled: true
    elasticsearch.ssl.verificationMode: none
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
    server.ssl.key: /usr/share/kibana/config/certs/tls.key
protocol: https
replicas: 1
resources:
  limits:
    cpu: 0.8
    memory: 2Gi
  requests:
    cpu: 0.1
    memory: 1Gi
secretMounts:
- name: default-tls
  path: /usr/share/kibana/config/certs
  secretName: default-tls
service:
  port: 5601
  type: ClusterIP

COMPUTED VALUES:
affinity: {}
elasticsearchHosts: https://es.example.com:9243
elasticsearchURL: ""
extraContainers: ""
extraEnvs:
- name: ELASTICSEARCH_USERNAME
  valueFrom:
    secretKeyRef:
      key: user
      name: es-creds
- name: ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: es-creds
- name: SERVER_HOST
  value: 0.0.0.0
extraInitContainers: ""
fullnameOverride: ""
healthCheckPath: /login
httpPort: 5601
image: elastic/kibana
imagePullPolicy: Always
imageTag: 8.0.0-SNAPSHOT
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  enabled: true
  hosts:
  - kibana.example.com
  path: /
  tls:
  - hosts:
    - kibana.example.com
    secretName: kibana-ingress-tls
kibanaConfig:
  kibana.yml: |
    kibana.disableWelcomeScreen: true
    telemetry.banner: false
    logging.quiet: true
    kibana.index: .kibana_k8s
    xpack.task_manager.index: .kibana_task_manager_k8s
    xpack.security.authc.providers: [basic]
    xpack.monitoring.enabled: true
    elasticsearch.ssl.verificationMode: none
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
    server.ssl.key: /usr/share/kibana/config/certs/tls.key
labels: {}
lifecycle: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: https
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 0.8
    memory: 2Gi
  requests:
    cpu: 0.1
    memory: 1Gi
secretMounts:
- name: default-tls
  path: /usr/share/kibana/config/certs
  secretName: default-tls
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  nodePort: ""
  port: 5601
  type: ClusterIP
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate

HOOKS:
MANIFEST:
---
# Source: kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-kibana-config
  labels:
    app: kibana
    release: "kibana"
data:
  kibana.yml: |
    kibana.disableWelcomeScreen: true
    telemetry.banner: false
    logging.quiet: true
    kibana.index: .kibana_k8s
    xpack.task_manager.index: .kibana_task_manager_k8s
    xpack.security.authc.providers: [basic]
    xpack.monitoring.enabled: true
    elasticsearch.ssl.verificationMode: none
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
    server.ssl.key: /usr/share/kibana/config/certs/tls.key
---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kibana
      release: "kibana"
  template:
    metadata:
      labels:
        app: kibana
        release: "kibana"
      annotations:
        
        configchecksum: 7a86f93b7fa405f7bcf6270617b09ab13cbb499e41cd10e31dac6d650173d5d
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: default-tls
          secret:
            secretName: default-tls
        - name: kibanaconfig
          configMap:
            name: kibana-kibana-config
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: "elastic/kibana:8.0.0-SNAPSHOT"
        imagePullPolicy: "Always"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "https://es.example.com:9243"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                key: user
                name: es-creds
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: es-creds
          - name: SERVER_HOST
            value: 0.0.0.0
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    #HERE is the issue
                    set -- -XGET -s --fail

                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
                    fi

                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "https://localhost:5601${path}")
                    if [[ "${STATUS}" -eq 200 ]]; then
                      exit 0
                    fi

                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
                    exit 1
                }

                http "/login"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 0.8
            memory: 2Gi
          requests:
            cpu: 0.1
            memory: 1Gi
        volumeMounts:
          - name: default-tls
            mountPath: /usr/share/kibana/config/certs
          - name: kibanaconfig
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
---
# Source: kibana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: kibana
    heritage: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
    - hosts:
      - kibana.example.com
      secretName: kibana-ingress-tls
  rules:
    - host: kibana.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana-kibana
              servicePort: 5601

```

**Describe the bug:**

The readinessProve never success because the return code is 302.

**Steps to reproduce:**

1. Deploy the Helm chart 
2. execute `kubectl describe KIBANE_POD` to see that the readinessProve is failing

**Expected behavior:**

The readinessProve should success.

**Provide logs and/or server output (if relevant):**

```
  Normal   Created    116s                kubelet, gke-dev-next-oblt-dev-next-oblt-pool-404d7f0c-fgxk  Created container kibana
  Normal   Started    116s                kubelet, gke-dev-next-oblt-dev-next-oblt-pool-404d7f0c-fgxk  Started container kibana
  Warning  Unhealthy  60s (x5 over 100s)  kubelet, gke-dev-next-oblt-dev-next-oblt-pool-404d7f0c-fgxk  Readiness probe failed: Error: Got HTTP code 000 but expected a 200
  Warning  Unhealthy  39s (x2 over 49s)   kubelet, gke-dev-next-oblt-dev-next-oblt-pool-404d7f0c-fgxk  Readiness probe failed: Error: Got HTTP code 302 but expected a 200
```

**Any additional context:**
