### ISSUE TITLE
How to start separated master and datanodes?

### ISSUE THREAD

**Issue by hatharom** [elastic/helm-charts#565]
Hi All!

I have this chart as a dependency in my main chart (helm-chart/elasticsearch and requirement.yml pointing to this directory).
I am wondering how to config this to launch node with a dedicated type (say only 'datanode')

In the values.yaml I can see only these: 

```
nodeGroup: "master"
masterService: ""
roles:
  master: "true"
  ingest: "true"
  data: "true"
replicas: 3
```
Which means that 3 replicas of an 'all-in-one' will be started.

I am able config this like this: X only master node and Y only data node?

Or should I include this chart twice in my main chart and and configure them separatly? In this case will they work out-of-the box and can see each other?
