### ISSUE TITLE
[metricbeat] daemonset.metricbeatConfig.metricbeat.yml not written to configmap

### ISSUE THREAD

**Issue by JWDobken** [elastic/helm-charts#594]
When you take the [values.yaml](https://github.com/elastic/helm-charts/blob/master/metricbeat/values.yaml) and make any changes to the metricbeat.yml of the daemon or the deployment e.g. change the host path. This does not effect the created configmap.

**MWE**

Take the [values.yaml](https://github.com/elastic/helm-charts/blob/master/metricbeat/values.yaml) and change the hostpath in `daemonset.metricbeatConfig.metricbeat.yml`:

```yml
-       output.elasticsearch:
            hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
+       output.elasticsearch:
            hosts: ['https://github.com']
```

Now create the manifest with helm template:

```cmd
helm template metricbeat elastic/metricbeat \
    --version 7.6.2 \
    --namespace monitoring \
    --output-dir manifest \
    --values values.yaml
```

Check the created `manifest/templates/configmap.yaml`:

```yaml
...
data:
  metricbeat.yml: |
    metricbeat.modules:
    ...
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

Chart version: 7.2.6
Kubernetes version: 1.17.3
Kubernetes provider: EKS
Helm Version: 3.1.1
