### ISSUE TITLE
[elasticsearch] Allow for configurable health status value in readinessProbe

### ISSUE THREAD

**Issue by rwittrick** [elastic/helm-charts#60]
In the elasticsearch statefulset readinessProbe command, the cluster health status has a hardcoded value of `green`.  It's not always the case that, as with coordinator nodes, green is the minimum acceptable state for cluster health.

**Comment by tgruenert** [comment]
I´ve run in the same issue at this moment. It would be nice to configure the required level within values. "green" can be default to be backwards compatible

```
readinessProbe.level: green
```

**Comment by rwittrick** [comment]
Doing that would add level to the configuration of the readinessProbe itself.  A couple of suggestions for the values file are:
1. Put the value at the top level outside of the readinessProbe
```
minClusterHealthStatus: green
```
2. Move the readinessProbe configuration fields under config, and the status field under readinessProbe
```
readinessProbe:
  config:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5
  minClusterHealthStatus: green
```
3. Similar to above, but put the status value more explicitly in the `command` key to differentiate it from k8s config
```
readinessProbe:
  config:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5
  command:
    minClusterHealthStatus: green
```

I'll work on a PR using option 3, for now
