### ISSUE TITLE
Use multiple elasticsearch hosts

### ISSUE THREAD

**Issue by refucktor** [elastic/helm-charts#603]
**Chart version:**
7.6.2

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AWS

**Helm Version:**
2.16.6

**Describe the bug:**
Trying to set multiple values in the `elasticsearchHosts`, turns out that is not able to parse the values. I already try to set the value in multiple ways. Could somebody just put a WORKING example of it.
 Here are some of the formats that I tried:

```
## Array example 1:
kibana.yml:
  elasticsearchHosts: '["http://es1:9200", "http://es2:9200", "http://es3:9200"]'

## Array example 2:
kibana.yml:
  elasticsearchHosts: ["http://es1:9200", "http://es2:9200", "http://es3:9200"]

## Array example 3:
kibana.yml:
  elasticsearchHosts:
  - http://es1:9200
  - http://es2:9200
  - http://es3:9200

## Array example 4:
kibana.yml:
  elasticsearchHosts:
    http://es1:9200
    http://es2:9200
    http://es3:9200
```

**Expected behavior:**
The helm is able to parse multiple values as array

**Provide logs and/or server output (if relevant):**
```
 FATAL  Error: [config validation of [elasticsearch].hosts]: types that failed validation:
- [config validation of [elasticsearch].hosts.0]: expected URI with scheme [http|https] but got [[http://es1:9200].
- [config validation of [elasticsearch].hosts.1]: expected value of type [array] but got [string]

```
