### ISSUE TITLE
Utilize the tpl function for logstashConfig and logstashPipeline

### ISSUE THREAD

**Issue by james-mchugh** [elastic/helm-charts#630]
**Describe the feature:**
When creating configmaps from the logstashPipeline and logstashConfig objects defined in values.yaml, it would be useful to use the `tpl` function. For example, this would change 

```yaml
{{- if .Values.logstashPipeline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstashPipeline }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
```
to:
```yaml
{{- if .Values.logstashPipeline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstashPipeline }}
  {{ $path }}: |
{{ tpl $config | indent 4 -}}
{{- end -}}
{{- end -}}
```

This is a small change, but it would give users a lot more power when supplying configs through the values.yaml.

**Describe a specific use case for the feature:**
Someone could use this to track the pipeline configs in a separate file than their values.yaml, allowing better organization and tracking. Instead of filling out the whole config via:

```yaml
logstashPipeline:
  logstash.conf: |
    # Insert config here...
```

Someone could do:
```yaml
logstashPipeline:
  logstash.conf: |
    {{ .Files.get "configs/logstash.yaml" }}
```

It would also allow the config files to have fields templated out as well.
