### ISSUE TITLE
[Kibana] Eviction of the pod

### ISSUE THREAD

**Issue by micborens** [elastic/helm-charts#643]
**Chart version:**
7.6.2
**Kubernetes version:**
v1.15.10-eks-bac369
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Amazon EKS
**Helm Version:**
v3.0.3

**My custom Values**
```
imageTag: "7.6.2"

elasticsearchHosts: "http://xxxxxx:9200"

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-proxy-headers: X-Forwarded-Proto:https||X-Forwarded-Port:443
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: xxxxxx
  path: /
  hosts:
    - xxxxx
fullnameOverride: "kibana"

resources:
  requests:
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=4096"

kibanaConfig:
  kibana.yml: |
    elasticsearch:
        pingTimeout: 10000
        requestTimeout: 30000
        shardTimeout: 30000
        startupTimeout: 10000
    logging.silent: true
```

**Describe the bug:**

I deployed kibana on my kubernetes but after few minutes he is consuming his ephemeral storage. Then pod is automatically `Evicted` and recreate everytime.

**Steps to reproduce:**

1. Deploy kibana and control disk space available

**Expected behavior:**

**Provide logs and/or server output:**

Message from the pod 
```
Pod The node had condition: [DiskPressure]
```

```
↳ k exec -it kibana-6f469888d8-pz887 -- bash
bash-4.2$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          15G   12G  3.0G  81% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1   15G   12G  3.0G  81% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.8G   12K  7.8G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.8G     0  7.8G   0% /proc/acpi
tmpfs           7.8G     0  7.8G   0% /sys/firmware
bash-4.2$
```

```
kibana-5677b68d9-2hnxq   0/1     Evicted   0          5h11m
kibana-5677b68d9-4tt8f   0/1     Evicted   0          3h34m
kibana-5677b68d9-58544   0/1     Evicted   0          125m
kibana-5677b68d9-5zwlm   0/1     Evicted   0          5h11m
kibana-5677b68d9-622xm   0/1     Evicted   0          125m
kibana-5677b68d9-85wbg   0/1     Evicted   0          7h31m
kibana-5677b68d9-8cqxv   0/1     Evicted   0          125m
kibana-5677b68d9-98bnl   0/1     Evicted   0          5h10m
kibana-5677b68d9-bjzpx   0/1     Evicted   0          125m
kibana-5677b68d9-cbvkm   0/1     Evicted   0          125m
kibana-5677b68d9-ccjsm   1/1     Running   0          28m
kibana-5677b68d9-gjr4m   0/1     Evicted   0          125m
kibana-5677b68d9-hsmfn   0/1     Evicted   0          125m
kibana-5677b68d9-j2r7h   0/1     Evicted   0          125m
kibana-5677b68d9-lmrp8   0/1     Evicted   0          125m
kibana-5677b68d9-nlqwl   0/1     Evicted   0          5h10m
kibana-5677b68d9-p94w2   0/1     Evicted   0          5h11m
kibana-5677b68d9-pggxl   0/1     Evicted   0          125m
kibana-5677b68d9-pmgw9   0/1     Evicted   0          5h11m
kibana-5677b68d9-qdr7f   0/1     Evicted   0          125m
kibana-5677b68d9-rl8qz   0/1     Evicted   0          5h10m
kibana-5677b68d9-swxxs   0/1     Evicted   0          5h11m
kibana-5677b68d9-x6jdw   0/1     Evicted   0          125m
kibana-5677b68d9-xrgpx   0/1     Evicted   0          125m
kibana-5677b68d9-z468t   0/1     Evicted   0          5h11m
kibana-5677b68d9-zcf5l   0/1     Evicted   0          5h10m
```

If anyone can help me to understand and solve this issue?
