### ISSUE TITLE
all shards failed while resizing PVC

### ISSUE THREAD

**Issue by getvivekv** [elastic/helm-charts#647]
Hi,

I am trying to setup a Graylog + Elasticsearch cluster on Azure ask. Initial setup works fine and I am able to see a working graylog that can receive data and save in elasticsearch. The problem comes up when I want to resize the elasticsearch PVC

Steps to setup
```
NAMESPACE=graylog-production
helm upgrade --install --namespace $NAMESPACE --values ./master.yaml elasticsearch-master elastic/elasticsearch
helm upgrade --install --namespace $NAMESPACE --values ./client.yaml elasticsearch-client elastic/elasticsearch
helm upgrade --install --namespace $NAMESPACE --values ./data.yaml elasticsearch-data elastic/elasticsearch
```

master.yaml

```
---
clusterName: "elasticsearch"
imageTag: 6.8.9
nodeGroup: "master"
roles:
  master: "true"
  ingest: "false"
  data: "false"
replicas: 3
esJavaOpts: "-Xmx3g -Xms3g"
resources:
  requests:
    cpu: "500m"
    memory: "5Gi"
  limits:
    cpu: "2000m"
    memory: "8Gi"
volumeClaimTemplate:
  resources:
    requests:
      storage: 4Gi
```

client.yaml
```
---
clusterName: "elasticsearch"
imageTag: 6.8.9
nodeGroup: "client"
roles:
  master: "false"
  ingest: "false"
  data: "false"
replicas: 2
resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "2Gi"
volumeClaimTemplate:
  resources:
    requests:
      storage: 1Gi
persistence:
  enabled: false
```

data.yaml
```
---
clusterName: "elasticsearch"
imageTag: 6.8.9
nodeGroup: "data"
roles:
  master: "false"
  ingest: "true"
  data: "true"
replicas: 3

esJavaOpts: "-Xmx2g -Xms2g"
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "5Gi"
volumeClaimTemplate:
  resources:
    requests:
      storage: "10Gi"
```

This creates 3 stateful sets with the names
elasticsearch-master
elasticsearch-client
elasticsearch-data

As per a documentation that I read on elastic website, in order to resize the PVC for data from 10G to 15G, I have changed "**nodeGroup**" to "**data-1**" and adjusted the **storage**

This removed the stateful set **elasticsearch-client** and created a new **elasticsearch-client-1**

After the pods are up, logging into graylog shows this message and apparently my logs are lost. 
It was my understanding that after changing the nodegroup, elasticsearch would create new set and migrate data. 

**Chart version:**
elastic https://helm.elastic.co

**Kubernetes version:**
1.16

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Azure

**Helm Version:**
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
