### ISSUE TITLE
StorageClassName not working

### ISSUE THREAD

**Issue by Espade** [elastic/helm-charts#656]
**Chart version:** elastic/elasticsearch: 7.7.1

**Kubernetes version:** 13.2

**Kubernetes provider:** None

**Helm Version:** v3.2.1

I am working with elasticsearch on kubernetes. I followed the README instructions to install elasticsearch. 

**Describe the bug:**

Even when I change the **storageClassName** in **volumeClaimTemplate**. Every time new pod always shows: ```Volumes ClaimName:  elasticsearch-master-elasticsearch-master-0```, and ```pod has unbound immediate PersistentVolumeClaims (repeated 4 times)```. 

**Steps to reproduce:**
1. helm install release-name  ./helm-charts/elasticsearch --set imageTag=7.7.1

**Expected behavior:**
Three pods are pending. When you type ```kubectl describe pod elasticsearch-master-0```, it will show **pod has unbound immediate PersistentVolumeClaims (repeated 4 times)**.

**Provide logs and/or server output (if relevant):**
```
Volumes:
  elasticsearch-master:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  elasticsearch-master-elasticsearch-master-0
    ReadOnly:   false
  default-token-lhrgq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lhrgq
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  7m40s (x2 over 7m40s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
```

**Comment by Espade** [comment]
1. helm get release-name
```
COMPUTED VALUES:
antiAffinity: hard
antiAffinityTopologyKey: kubernetes.io/hostname
clusterHealthCheckParams: wait_for_status=green&timeout=1s
clusterName: elasticsearch
envFrom: []
esConfig: {}
esJavaOpts: -Xmx1g -Xms1g
esMajorVersion: ""
extraContainers: []
extraEnvs: []
extraInitContainers: []
extraVolumeMounts: []
extraVolumes: []
fsGroup: ""
fullnameOverride: ""
httpPort: 9200
image: docker.elastic.co/elasticsearch/elasticsearch
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.7.1
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
initResources: {}
keystore: []
labels: {}
lifecycle: {}
masterService: ""
masterTerminationFix: false
maxUnavailable: 1
minimumMasterNodes: 2
nameOverride: ""
networkHost: 0.0.0.0
nodeAffinity: {}
nodeGroup: master
nodeSelector: {}
persistence:
  annotations: {}
  enabled: true
  storageClass: local-path
podAnnotations: {}
podManagementPolicy: Parallel
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
podSecurityPolicy:
  create: false
  name: ""
  spec:
    fsGroup:
      rule: RunAsAny
    privileged: true
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - secret
    - configMap
    - persistentVolumeClaim
priorityClassName: ""
protocol: http
rbac:
  create: false
  serviceAccountName: ""
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 3
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi
roles:
  data: "true"
  ingest: "true"
  master: "true"
schedulerName: ""
secretMounts: []
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
service:
  annotations: {}
  httpPortName: http
  labels: {}
  labelsHeadless: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  nodePort: ""
  transportPortName: transport
  type: ClusterIP
sidecarResources: {}
sysctlInitContainer:
  enabled: true
sysctlVmMaxMapCount: 262144
terminationGracePeriod: 120
tolerations: []
transportPort: 9300
updateStrategy: RollingUpdate
volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
```
2. kubectl get pv
```
pvc-871bcaa2-ab1b-11ea-8f64-ac1f6b803f42   30Gi       RWO            Delete           Bound    graph/data-graph-elasticsearch-data-0             local-path               13h
pvc-87413550-ab1b-11ea-8f64-ac1f6b803f42   4Gi        RWO            Delete           Bound    graph/data-graph-elasticsearch-master-0           local-path               13h
```
3. kubectl get pvc
```
data-graph-elasticsearch-data-0               Bound     pvc-871bcaa2-ab1b-11ea-8f64-ac1f6b803f42   30Gi       RWO            local-path     13h
data-graph-elasticsearch-master-0             Bound     pvc-87413550-ab1b-11ea-8f64-ac1f6b803f42   4Gi        RWO            local-path     13h
elasticsearch-master-elasticsearch-master-0   Pending                                                                                       21h
elasticsearch-master-elasticsearch-master-1   Pending                                                                                       21h
elasticsearch-master-elasticsearch-master-2   Pending                                                                                       21h
```
4. kubectl get events
```
37m         Warning   FailedScheduling   Pod                     pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
37m         Warning   FailedScheduling   Pod                     pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
37m         Warning   FailedScheduling   Pod                     pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
```
