### ISSUE TITLE
readinessProbe don't woking exacly

### ISSUE THREAD

**Issue by nvthuong1996** [elastic/helm-charts#675]
first start elastic search start exacly. when it starts to have data and restart readinessProbe does not check container when it ready

I tried removing readinessProbe in statefullset. And it works normally

**Chart version:**
7.8.0

**Kubernetes version:**:
 v1.17.6

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
RKE

**Helm Version:**
v3.2.2

Value
```
  nodeSelector:
    kubernetes.io/hostname: woker3
  replicas: 1
  volumeClaimTemplate:
    volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "storage-pv-elasticsearch"
    resources:
      requests:
        storage: 100Gi
  extraInitContainers: |
    - name: create
      image: busybox:1.28
      command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
      securityContext:
        runAsUser: 0
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: "{{ template "elasticsearch.uname" . }}"
    - name: file-permissions
      image: busybox:1.28
      securityContext:
        runAsUser: 0
      command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: "{{ template "elasticsearch.uname" . }}"
```
