### ISSUE TITLE
Helm test does not include image pull policy

### ISSUE THREAD

**Issue by fhaase2** [elastic/helm-charts#701]
The helm test does not get the image pull policy. Its not set at all. This can lead to issues.

**Comment by jmlrt** [comment]
Hi @fhaase2, can you be more explicit about how this can lead to issues?

**Comment by fhaase2** [comment]
Yes sure. When i run `helm test` it starts the container that is specified here:

```
  containers:
  - name: "{{ .Release.Name }}-{{ randAlpha 5 | lower }}-test"
    image: "{{ .Values.image }}:{{ .Values.imageTag }}"
    command:
      - "sh"
      - "-c"
      - |
        #!/usr/bin/env bash -e
        curl -XGET --fail '{{ template "elasticsearch.uname" . }}:{{ .Values.httpPort }}/_cluster/health?{{ .Values.clusterHealthCheckParams }}'
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 4 }}
```

ImagePullSecret is set and also the image name. But image pull policy is not. If i set a specific pullPolicy on the main values, it does not forward these to the test. Running `helm test` will fail, because image cannot be pulled for example.
