### ISSUE TITLE
Multiple pipeline supported (pipelines.yaml)

### ISSUE THREAD

**Issue by teebu** [elastic/helm-charts#746]
This should be added to the docs somewhere.

**Describe the feature:**
Usage of pipelines.yaml and to specify pipeline.id and path.

**Describe a specific use case for the feature:**
To be able to run multiple pipelines https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

After declaring your pipelines, modify the config to point to the files:

```
logstashConfig:
  logstash.yml: |
   ...
  pipelines.yml: |
    # This file is where you define your pipelines. You can define multiple.
    # For more information on multiple pipelines, see the documentation:
    #   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/logstash.conf"
    - pipeline.id: secondpipeline
      path.config: "/usr/share/logstash/pipeline/secondpipeline.conf"
```
