### ISSUE TITLE
Elasticsearch Production Ready helm chart

### ISSUE THREAD

**Issue by harsh4870** [elastic/helm-charts#750]
i have simply deployed ES helm chart just by changing version to 7.3.2 it's working well.

Just want to confirm here is this chart production-ready. i can see three nodes are there and all are `master` and `data` nodes both together. 

https://github.com/elastic/helm-charts/tree/master/elasticsearch

Is it a good way to go with or should i install another release of helm chart for data nodes as mention in `readme.md` by changing roles in `values.yaml`

Right now my config is like

```
clusterName: "elasticsearch"
nodeGroup: "master"

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: ""

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "true"
  ingest: "true"
  data: "true"

replicas: 3
minimumMasterNodes: 2
esMajorVersion: ""
```

What is the best practices? 

will be having around 2 to 3 indexes max with lots of amount data.
