### ISSUE TITLE
Dynamic refreshing of nginx, php-fpm, etc., hosts in a dynamic environment like kubernetes

### ISSUE THREAD

**Issue by poor-bob** [elastic/helm-charts#761]
Hosts need to be dynamic in an environment like Kubernetes.

In my use case, I needed php-fpm and nginx to have a dynamic list of IP addresses (endpoints) because my nginx/php pods are refreshed with every deployment. 

Example:
```
  # Nginx hosts
  hosts: [service-name]
```

Was not good enough. The metricbeat stubstatus requests were routed through the service load balancer.

**Comment by poor-bob** [comment]
You can actually achieve this with how well designed the chart architecture is. Props for that. I'm not sure if a solution like this could be baked in to metricbeat, but for those needing the solution now, this is what I ended up doing:

hot reloading in deployment.metricbeatConfig.metricbeat.yml:
```
        metricbeat.config.modules:
          path: ${path.config}/modules.d/*.yml
          reload.enabled: true
          reload.period: 10s
```

A shared volume to allow the sidecar container to modify files that metricbeat can monitor for changes and reload when necessary
```
    extraVolumes:
    - name: extra-configs
      emptyDir: {}
    extraVolumeMounts:
    - name: extra-configs
      mountPath: /usr/share/metricbeat/modules.d
      readOnly: false
```

extraContainers config
```
  extraContainers: |
    - name: kubernetes-endpoints-refresher
      image: us.gcr.io/.../kubernetes-endpoints-refresher:latest
      env:
      - name: NGINX_FILE_PATH
        value: /usr/share/modules.d/nginx.yml
      - name: PHP_FILE_PATH
        value: /usr/share/modules.d/php-fpm.yml
      - name: LOAD_IN_CLUSTER_CONFIG
        value: 'True'
      volumeMounts:
      - name: extra-configs
        mountPath: /usr/share/modules.d
        readOnly: false
```

endpoints_refresher.py:
```
#!/usr/bin/python
import sys
import os
from kubernetes import client, config

class App:
    def __init__(self):
        self.nginxFilePath = os.getenv('NGINX_FILE_PATH', 'nginx.yml')
        self.phpFilePath = os.getenv('PHP_FILE_PATH', 'php-fpm.yml')
        self.loadInClusterConfig = os.getenv('LOAD_IN_CLUSTER_CONFIG', False)
        self.endpoint = os.getenv('ENDPOINT', '... defaults ommitted as theyre specific to my usecase')
        self.containerPort = os.getenv('CONTAINER_PORT', 8080)
        self.namespace = os.getenv('NAMESPACE', '...')

    def run(self):
        self.setup()
        self.hotReload(10)

    def setup(self):
        self.makeNginxConfig()
        self.makePhpConfig()

    def retrieveEndpoints(self):
        # Configs can be set in Configuration class directly or using helper utility
        if (self.loadInClusterConfig):
            config.load_incluster_config()
        else:
            config.load_kube_config()

        v1 = client.CoreV1Api()
        ret = v1.read_namespaced_endpoints(self.endpoint, self.namespace)

        endpoints = []

        for i in ret.subsets[0].addresses:
            endpoints.append('http://' + i.ip + ':' + self.containerPort)

        return ",".join(endpoints)

    def makeNginxConfig(self):
        print("Making nginx config file for %s", self.endpoint)
        endpoints = self.retrieveEndpoints()

        f = open(self.nginxFilePath, "w")
        f.write("""
# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-nginx.html

- module: nginx
  metricsets:
  - stubstatus
  period: 10s
  enabled: true

  # Nginx hosts
  hosts: [{hosts}]

  # Path to server status. Default server-status
  server_status_path: "nginx_status..."
""".format(hosts=endpoints))
        f.close()

    def makePhpConfig(self):
        print("Making php config file for %s", self.endpoint)
        endpoints = self.retrieveEndpoints()

        f = open(self.phpFilePath, "w")
        f.write("""
# Module: php_fpm
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-php_fpm.html

- module: php_fpm
  metricsets:
  - pool
  #- process
  period: 10s
  enabled: true

  # Nginx hosts
  hosts: [{hosts}]

  # Path to server status. Default server-status
  status_path: "/status"    
""".format(hosts=endpoints))
        f.close()

    def hotReload(self, frequency, endpoints=[]):
        newEndpoints = self.retrieveEndpoints()
        if (endpoints == newEndpoints):
            print("Nothing to refresh")
        else:
            print("Hot reloading endpoints {endpoints}")
        time.sleep(frequency)
        self.hotReload(frequency, newEndpoints)

if __name__ == '__main__':
    App().run()
```

Dockerfile
```
FROM python:3

WORKDIR /usr/share/

RUN pip install --no-cache-dir kubernetes

COPY kubernetes-endpoints-refresher/ .

CMD [ "python", "endpoints_refresher.py" ]

```
