### ISSUE TITLE
monitore elasticsearch cluster with metricbeat

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#766]
**Describe the feature:**

Some Helm charts, provide monitoring with the application, (the most famous is "prometheus exporter"). By example, https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch .

Since elastic has a product ``metricbeat`` , what about to propose a metricbeat instance as cluster side

**Describe a specific use case for the feature:**

Monitore ES cluster in production.

**Comment by jmlrt** [comment]
Hi @ebuildy,
It is possible and recommended to deploy [Metricbeat chart](https://github.com/elastic/helm-charts/tree/7.9/metricbeat) to monitor [Elasticsearch chart](https://github.com/elastic/helm-charts/tree/7.9/elasticsearch) chart.

**Comment by ebuildy** [comment]
Yes I understand, 

Most of Helm charts, have **monitoring defined as template** , via servicemonitor.yaml: https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/servicemonitor.yaml.

Will be good to have a similar thing with metricbeat.

**Comment by cambierr** [comment]
Shouldn't we instead have a companion container for each es pod ? so that they are each collected independently ?

**Comment by jmlrt** [comment]
> Shouldn't we instead have a companion container for each es pod ? so that they are each collected independently ?

This is not required and not recommended.

You should use Metricbeat deployment pod in Metricbeat chart with [Elasticsearch module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html) to monitor Elasticsearch.

Actually unlike with Prometheus, we don't need anything into Elasticsearch chart for that.

The only thing you need is to add the following config into Metricbeat values:

```yaml
deployment:
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: elasticsearch
        metricsets:
          - node
          - node_stats
        period: 10s
        hosts: ["elasticsearch-master:9200"]
```
