### ISSUE TITLE
Readiness probe failed: Error: Got HTTP code 503 but expected a 200

### ISSUE THREAD

**Issue by melissajenner22** [elastic/helm-charts#780]
**Chart version:**
7.7.1
**Kubernetes version:**
1.16
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS
**Helm Version:**
2.16.10

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
helm get kibana

REVISION: 1
RELEASED: Thu Aug 13 20:14:45 2020
CHART: kibana-7.7.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
elasticsearchHosts: http://elasticsearch-master:9200
elasticsearchURL: ""
envFrom: []
extraContainers: ""
extraEnvs:
- name: NODE_OPTIONS
  value: --max-old-space-size=1800
extraInitContainers: ""
fullnameOverride: ""
healthCheckPath: /app/kibana
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.7.1
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
kibanaConfig: {}
labels: {}
lifecycle: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 800m
    memory: 1Gi
secretMounts: []
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  nodePort: ""
  port: 5601
  type: ClusterIP
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate

HOOKS:
MANIFEST:

---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  labels: 
    app: kibana
    release: "kibana"
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-kibana
  labels: 
    app: kibana
    release: "kibana"
    heritage: Tiller
spec:
  replicas: 1
  strategy:
    type: Recreate
    
  selector:
    matchLabels:
      app: kibana
      release: "kibana"
  template:
    metadata:
      labels:
        app: kibana
        release: "kibana"
      annotations:
        
    spec:
      securityContext:
        fsGroup: 1000
        
      volumes:
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          
        image: "docker.elastic.co/kibana/kibana:7.7.1"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch-master:9200"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: NODE_OPTIONS
            value: --max-old-space-size=1800
          
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    set -- -XGET -s --fail -L

                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
                    fi

                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
                    if [[ "${STATUS}" -eq 200 ]]; then
                      exit 0
                    fi

                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
                    exit 1
                }

                http "/app/kibana"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 800m
            memory: 1Gi
          
        volumeMounts:

```

</details>

**Describe the bug:**
```
kubectl describe pod kibana-kibana-7458222222-2222

  Warning  Unhealthy  26m (x5 over 27m)  kubelet, ip-101-10-161-126.us-west-2.compute.internal  Readiness probe failed: Error: Got HTTP code 000 but expected a 200
  Warning  Unhealthy  26m                kubelet, ip-101-10-161-126.us-west-2.compute.internal  Readiness probe failed: Error: Got HTTP code 503 but expected a 200
```

**Steps to reproduce:**

1.
helm install --name elasticsearch ./elasticsearch --namespace elk
2.
helm install --name kibana ./kibana --namespace elk
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by kudrew** [comment]
I have a similar issue on GKE: exposing the service for Kibana (Nodeport/ LoadBalancer) via Ingress because the health check keeps failing on v.7.8.1 (presumably hitting "/" receives error 302, but "/app/kibana" gives 200. The path that the health check looks for  is "/").

```

{"type":"log","@timestamp":"2020-08-17T19:27:00Z","tags":["listening","info"],"pid":7,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2020-08-17T19:27:01Z","tags":["info","http","server","Kibana"],"pid":7,"message":"http server running at http://0.0.0.0:5601"}
...
...
...
{"type":"response","@timestamp":"2020-08-17T20:27:59Z","tags":[],"pid":7,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"10.150.12.81","user-
agent":"GoogleHC/1.0","connection":"Keep-alive"},"remoteAddress":"10.150.12.81","userAgent":"10.150.12.81"},"res":{"statusCode":302,"responseTime":20,"contentLength":9},"messag
e":"GET / 302 20ms - 9.0B"}
{"type":"response","@timestamp":"2020-08-17T20:27:59Z","tags":[],"pid":7,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"10.150.12.
79","user-agent":"GoogleHC/1.0","connection":"Keep-alive"},"remoteAddress":"10.150.12.79","userAgent":"10.150.12.79"},"res":{"statusCode":200,"responseTime":56,"contentLength":
9},"message":"GET /app/kibana 200 56ms - 9.0B"}
```

**Comment by melissajenner22** [comment]
In helm-charts/elasticsearch/values.yaml, at line 236, I changed / to /app/kibana (Note: helm version 2.16.10. Kuberketes version 1.16 (eks))

```
231 ingress:
232   enabled: false
233   annotations: {}
234     # kubernetes.io/ingress.class: nginx
235     # kubernetes.io/tls-acme: "true"
236   path: /app/kibana
237   hosts:
238     - chart-example.local
239   tls: []
240   #  - secretName: chart-example-tls
241   #    hosts:
242   #      - chart-example.local

$ helm install --name elasticsearch ./elasticsearch --namespace elk

$ kubectl get pod
NAME                     READY   STATUS    RESTARTS   AGE
elasticsearch-master-0   1/1     Running   0          7m46s
elasticsearch-master-1   1/1     Running   0          7m46s
elasticsearch-master-2   1/1     Running   0          7m46s

$ kubectl describe pod elasticsearch-master-0

  Warning  Unhealthy               7m30s (x2 over 7m40s)  kubelet, ip-10-117-56-142.us-west-2.compute.internal  Readiness probe failed: Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )
Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )


$ git diff
diff --git a/elasticsearch/values.yaml b/elasticsearch/values.yaml
index 284ea67..2e4afb7 100755
--- a/elasticsearch/values.yaml
+++ b/elasticsearch/values.yaml
@@ -233,7 +233,7 @@ ingress:
   annotations: {}
     # kubernetes.io/ingress.class: nginx
     # kubernetes.io/tls-acme: "true"
-  path: /
+  path: /app/kibana
   hosts:
     - chart-example.local
   tls: []

```
Which file and line did you mean to change / to /app/kibana?

**Comment by Ankitchandre** [comment]
you can change  the value of healthCheckPath:  from "/app/kibana"  to "/api/status"  in values.yaml . This should pass the readiness probe error .

**Comment by abdennour** [comment]
But if i have to change `healthCheckPath` to a new value , why is not the default value ? 
Guys, please check best practices implemented in som helm git repos ( e.g: bitnami,.. etc) and mimic them.
Overall, good job! thanks!

**Comment by shmelkin** [comment]
This is apparently still not working properly or may have different reasons.

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
kubeadm version

```
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:24:08Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
kibana values.yaml
```
elasticsearchHosts: "https://redacted"

extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1800"
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey



secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/kibana/config/certs-gen/


kibanaConfig:
  kibana.yml: |
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs-gen/privkey2.pem
      certificate: /usr/share/kibana/config/certs-gen/fullchain2.pem
    xpack.reporting.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}

protocol: https

service:
  type: NodePort
  loadBalancerIP: ""
  port: 5601
  nodePort: 30002
  labels: {}
  annotations: {}
  loadBalancerSourceRanges: []
  httpPortName: http

healthCheckPath: /api/status # also checked /app/kibana and default
```

kubectl get pv,pvc,nodes,pods,svc

```
NAME                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                 STORAGECLASS   REASON   AGE
persistentvolume/elk-data   30Gi       RWO            Retain           Bound    default/elasticsearch-master-elasticsearch-master-0                           51m

NAME                                                                STATUS   VOLUME     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/elasticsearch-master-elasticsearch-master-0   Bound    elk-data   30Gi       RWO                           51m

NAME               STATUS   ROLES                  AGE   VERSION
node/disposable1   Ready    control-plane,master   54m   v1.23.3

NAME                                    READY   STATUS    RESTARTS   AGE
pod/elasticsearch-master-0              1/1     Running   0          34m
pod/kibana-kibana-79544d8d54-x4smn      0/1     Running   0          67s
pod/nginx-deployment-55784d5d88-mc4tt   1/1     Running   0          51m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
service/elasticsearch-master            NodePort    10.97.220.72    <none>        9200:30001/TCP,9300:30786/TCP   34m
service/elasticsearch-master-headless   ClusterIP   None            <none>        9200/TCP,9300/TCP               34m
service/kibana-kibana                   NodePort    10.96.230.182   <none>        5601:30002/TCP                  67s
service/kubernetes                      ClusterIP   10.96.0.1       <none>        443/TCP                         54m
service/nginx-service                   NodePort    10.108.60.203   <none>        80:30000/TCP                    51m
```

kubectl describe pod/kibana-kibana-79544d8d54-x4smn

```
Name:         kibana-kibana-79544d8d54-x4smn
Namespace:    default
Priority:     0
Node:         disposable1/172.26.120.72
Start Time:   Thu, 17 Feb 2022 10:46:50 +0100
Labels:       app=kibana
              pod-template-hash=79544d8d54
              release=kibana
Annotations:  cni.projectcalico.org/containerID: f5011b7ee549f8b4983e09735bae0fad6584c662e14b558df5cd1bc6ce064839
              cni.projectcalico.org/podIP: 192.168.47.16/32
              cni.projectcalico.org/podIPs: 192.168.47.16/32
              configchecksum: 7ce114df53c5a41b1c4386587d8c9a3b5aebf96f5137051574760a6a72d488e
Status:       Running
IP:           192.168.47.16
IPs:
  IP:           192.168.47.16
Controlled By:  ReplicaSet/kibana-kibana-79544d8d54
Containers:
  kibana:
    Container ID:   containerd://5130c671a35f1f8fbcd1ccd06a6d8a4ae9c047c29e42ee883b246940118b1179
    Image:          docker.elastic.co/kibana/kibana:7.16.3
    Image ID:       docker.elastic.co/kibana/kibana@sha256:6c9867bd8e91737db8fa73ca6f522b2836ed1300bcc31dee96e62dc1e6413191
    Port:           5601/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 17 Feb 2022 10:46:51 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      1
      memory:   2Gi
    Readiness:  exec [sh -c #!/usr/bin/env bash -e

# Disable nss cache to avoid filling dentry cache when calling curl
# This is required with Kibana Docker using nss < 3.52
export NSS_SDB_USE_CACHE=no

http () {
    local path="${1}"
    set -- -XGET -s --fail -L

    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
    fi

    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "https://localhost:5601${path}")
    if [[ "${STATUS}" -eq 200 ]]; then
      exit 0
    fi

    echo "Error: Got HTTP code ${STATUS} but expected a 200"
    exit 1
}

http "/api/status" # also checked /app/kibana and default
] delay=10s timeout=5s period=10s #success=3 #failure=3
    Environment:
      ELASTICSEARCH_HOSTS:     https://redacted:30001
      SERVER_HOST:             0.0.0.0
      NODE_OPTIONS:            --max-old-space-size=1800
      ELASTICSEARCH_USERNAME:  <set to the key 'username' in secret 'elastic-credentials'>  Optional: false
      ELASTICSEARCH_PASSWORD:  <set to the key 'password' in secret 'elastic-credentials'>  Optional: false
      KIBANA_ENCRYPTION_KEY:   <set to the key 'encryptionkey' in secret 'kibana'>          Optional: false
    Mounts:
      /usr/share/kibana/config/certs-gen/ from elastic-certificates (rw)
      /usr/share/kibana/config/kibana.yml from kibanaconfig (rw,path="kibana.yml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6p92j (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  elastic-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elastic-certificates
    Optional:    false
  kibanaconfig:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kibana-kibana-config
    Optional:  false
  kube-api-access-6p92j:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  112s               default-scheduler  Successfully assigned default/kibana-kibana-79544d8d54-x4smn to disposable1
  Normal   Pulled     111s               kubelet            Container image "docker.elastic.co/kibana/kibana:7.16.3" already present on machine
  Normal   Created    111s               kubelet            Created container kibana
  Normal   Started    111s               kubelet            Started container kibana
  Warning  Unhealthy  2s (x11 over 92s)  kubelet            Readiness probe failed: Error: Got HTTP code 503 but expected a 200
```
