### ISSUE TITLE
Cannot set custom podAntiAffinity

### ISSUE THREAD

**Issue by ghost** [elastic/helm-charts#835]
**Chart version:**
Logstash

**Description**
In the logstash helm chart, it is not possible to set an additional, custom, podAntiAffinity rule.
In the statefulset definition, antiaffinity is only used to prevent to logstash from running on the same topology domain.
It would be great to be able to add custom podAntiAffinity rules.

**Comment by ebuildy** [comment]
Something like that:

statefulset.yaml, line 86:

```
{{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "{{ template "logstash.fullname" .}}"
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ template "logstash.fullname" . }}"
      {{- else }}
        {{- with .Values.antiAffinity }}
        podAntiAffinity:
{{ toYaml . | indent 10 }}    
      {{- end }}
      {{- end }}
```
