### ISSUE TITLE
Inject node IP to Metricbeat daemonset for kubelet communication

### ISSUE THREAD

**Issue by gburton1** [elastic/helm-charts#873]
**Describe the feature:**

Currently, the Metricbeat chart gives access to NODE_NAME in the daemonset via the Downward API, to be used for talking to the kubelet of the hosting node:

```
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

It would be helpful to also have the NODE_IP as an option to use for that communication:
```
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
```

The proposed change is to simply add the snippet above to the ENV section of the metricbeat container here https://github.com/elastic/helm-charts/blob/cc19a785cdb3ff06f6a64232d3cada27428dc620/metricbeat/templates/daemonset.yaml#L127..L135

That would make it possible for people to use it here: `hosts: ["https://${NODE_IP}:10250"]`. The current default behavior of using NODE_NAME would stay the same.

**Describe a specific use case for the feature:**

When managing Kubernetes nodes as cattle whose lives are very short, there is no need to register them with a DNS server. For local communication from a pod to its host machine, hitting the IP directly is ideal. Here is an example from another common Helm chart (for Datadog) that also needs to harvest metrics from the kubelet secure port, and does it by injecting the host IP:

https://github.com/DataDog/helm-charts/blob/fc9d6ffbc5e9f4531c9bf2b5170bf6eda7b20e37/charts/datadog/templates/containers-common-env.yaml#L10..L13
