### ISSUE TITLE
Elasticsearch: Allow specifying extraContainers as a map

### ISSUE THREAD

**Issue by musabhusaini** [elastic/helm-charts#874]
**Describe the feature:**
Currently, the Elasticsearch chart supports specifying `extraContainers` as a YAML array (or a templatable string for backward compatibility). This is fine for simple use cases, but not convenient if overriding via multiple values files is desired.

This feature request is to additionally support providing `extraContainers` as a map, which would facilitate overrides through multiple layers of values files.

**Describe a specific use case for the feature:**

Consider a simple `my-values.yaml` file:

``` yaml
extraContainers:
- name: do-something
  image: my-image
  command: ['do', 'something']
```

I want to make use of helm's file merging to override the image name in subsequent deploy steps using a separate `my-values.override.yaml` file. Under the current implementation, this will require me to duplicate the entire spec:

``` yaml
extraContainers:
- name: do-something
  image: my-override-image
  command: ['do', 'something']
```

This repetition is not convenient and will cause a lot of maintenance issues. The proposed implementation would be to allow expressing `my-values.yaml` like so:

``` yaml
extraContainers:
  something:
    name: do-something
    image: my-image
    command: ['do', 'something']
```

Which could then be overridden by another `my-values.override.yaml`:

``` yaml
extraContainers:
  something:
    image: my-override-image
```
