### ISSUE TITLE
Cannot mount elasticsearch keystore in pod, device busy

### ISSUE THREAD

**Issue by jhouston1604** [elastic/helm-charts#90]
I'm trying to mount the elasticsearch keystore per the documentation but I keep getting the error below. I've verified the the elasticsearch keystore file is valid (by adding it to a test continer and testing the values).
###  Error:
```Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp /usr/share/elasticsearch/config/elasticsearch.keystore: Device or resource busy```

### Steps taken:
1. Command to create the secret:
`kubectl create secret generic elasticsearch-keystore --from-file=./elasticsearch.keystore`

2. SecretMounts in my yaml configuration:
``` 
  secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/elasticsearch/config/certs
  - name: elastic-license
    secretName: elastic-license
    path: /usr/share/elasticsearch/config/license
  - name: elasticsearch-keystore
    secretName: elasticsearch-keystore
    path: /usr/share/elasticsearch/config/elasticsearch.keystore
    subPath: elasticsearch.keystore 
```

Is there something I am missing?
