### ISSUE TITLE
EKS Storage Volume Support

### ISSUE THREAD

**Issue by NEPDAVE** [elastic/helm-charts#97]
I see that this Chart is tested against GKE. I work at Nike and we are using EKS. 

According to the Helm Chart documentation, I believe the only thing I need to change in the `values.yaml` file is the `storageClassName: "standard"` variable to `storageClassName: "gp2"`

I have verified that the cluster does, in fact, have a storage class set up. However, when I go to deploy the Chart and I describe my master elasticsearch nodes, I am getting this error message:

`pod has unbound immediate PersistentVolumeClaims (repeated 3 times)`

I believe that I am still missing some configuration setting having to do with Storage. Please let me know if you need any additional information. Any help is appreciated.

**Comment by Crazybus** [comment]
> I work at Nike and we are using EKS.

While we don't have any automated testing yet for EKS it has been manually confirmed to work. As long as the Kubernetes provider has some kind of persistent storage (which EKS does) it's going to work just fine. 

Have you been able to run other statefulsets with the same `volumeClaimTemplate` configuration? 

Could you give me the following to help debug:

* Your values.yaml configuration (mostly interested in the `volumeClaimTemplate` settings).
* Output of the following commands:

```
kubectl get sc
kubectl get pvc
kubectl get events
kubectl get sts elasticsearch-master -o yaml # (or whatever your deployment is called)
kubectl describe pod elasticsearch-master-0
```

**Comment by NEPDAVE** [comment]
[output.txt](https://github.com/elastic/helm-charts/files/3096022/output.txt)

Thank you for getting back to me! It is much appreciated. We tried a workaround that fixed the original error message. Not sure if this is a "real" workaround, dumb luck, or something else. I have also attached the requested output. The output is from the current configuration which is not encountering the original error message. 

Again, here is the original error message:
`pod has unbound immediate PersistentVolumeClaims (repeated 3 times)`

The steps taken for the "workaround" are here:

We created a new storage class on the cluster named "elasticsearch" of type "gp2". 

Her is the yaml:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elasticsearch
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
```

In the `values.yaml` file we changed the `storageClassName: "standard"` variable to `storageClassName: "elasticsearch"`. 

Here is the `volumeClaimTemplate` section taken from loading the `vaules.yalm`  variables into the `statefulset.yaml` template:
```
volumeClaimTemplates:
  - metadata:
      name: elasticsearch-master
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: elasticsearch
```

Deploying this configuration via Helm worked. We then deleted the resources from the "workaround" configuration and tried going back to our "original" configuration - IE we changed the `values.yaml` file `storageClassName: "standard"` variable to `storageClassName: "gp2"` . and deployed again via Helm and this also worked. 

Here is the `volumeClaimTemplate` we currently have in the cluster:
```
volumeClaimTemplates:
  - metadata:
      name: elasticsearch-master
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: gp2
```
We are going to continue testing this for a proof of concept. Thank you for your help. Please let me know if you have any questions or require additional information.
