### ISSUE TITLE
 how can override values of  output.elasticsearch.hosts inside the default helm chart of elastic/filebeat using --set option?

### ISSUE THREAD

**Issue by saidev680** [elastic/helm-charts#976]
Client Version: v1.19.4
Server Version: v1.17.9-eks-a84824

*Kubernetes provider: - Amazon EKS

Helm Version: - v3.4.1

helm get release output

e.g. helm install filebeat

I am using the elastic filebeat repo to install filebeat helm chart.

1.  command used : helm upgrade --install filebeat elastic/filebeat  --set output.elasticsearch.username=$username  --set output.elasticsearch.password=$password  -f ./custom-values/filebeat/values.yaml

I am passing the custom values from -f ./custom-values/filebeat/values.yaml and . 

but the values  output.elasticsearch.username are not getting set through --set option

how can we set those values to helm chart.

OR

for example how can override values of  output.elasticsearch.hosts inside the default helm chart of elastic/filebeat using --set option?

**Comment by jmlrt** [comment]
Hi @saidev680,

`output.elasticsearch.hosts` is not a valid value for this chart.

You need to use:
```yaml
filebeatConfig:
  filebeat.yml: |
    # full content of the filebeat.yml config file
    # ...
```

I don't think there is a way to pass it through the command line using `--set` option.

**Comment by saidev680** [comment]
but we can not keep values directly in  output.elasticsearch.hosts inside 

filebeatConfig:
  filebeat.yml: |
    # full content of the filebeat.yml config file
    # ...



because
 1. those values are changing as per env
 2. those are secret values.


is there any way to keep those values dynamic and use along with helm install command?

**Comment by jmlrt** [comment]
I would recommand passing these values as environment variables instead and referencing the environment variables in `filebeatConfig` value.

You can find an example where environment variables for Elasticsearch username and password are retrieved from a K8S secret which is the recommended way:

https://github.com/elastic/helm-charts/blob/b411ca6ca8a9a6860b45b44b3654f0b78e68e059/filebeat/examples/security/values.yaml#L27-L37

These environment variables are then passed to Filebeat config:

https://github.com/elastic/helm-charts/blob/b411ca6ca8a9a6860b45b44b3654f0b78e68e059/filebeat/examples/security/values.yaml#L14-L16

You can also use `ELASTICSEARCH_HOST` and `ELASTICSEARCH_PORT` variables for the host (more details in [Run Filebeat on Kubernetes](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html#_settings)).

If you don't want to use K8S secrets, you can create a specific value file for each environment with only the `extraEnvs` values for credentials:

```yaml
# production-values.yml
extraEnvs:
  - name: 'ELASTICSEARCH_HOST'
    value: 'elasticsearch.example.com'
  - name: 'ELASTICSEARCH_USERNAME'
    value: 'elastic'
  - name: 'ELASTICSEARCH_PASSWORD'
    value: 'changeme'
```

If you really want to pass these variables from `helm` command line, this is a bit tricky but you should be able to use something like `--set extraEnvs[0].name=ELASTICSEARCH_HOST --set extraEnvs[0].value=elasticsearch.example.com --set extraEnvs[1].name=ELASTICSEARCH_USERNAME --set extraEnvs[1].value=elastic --set extraEnvs[2].name=ELASTICSEARCH_PASSWORD --set extraEnvs[2].value=changeme` (not tested) (see [Helm doc](https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values) for more details on this syntax).

**Comment by knkarthik** [comment]
@jmlrt https://github.com/elastic/helm-charts/issues/976#issuecomment-749006664 didn't work for me. I'm using:
```
filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            default_indexers.enabled: true
            default_matchers.enabled: true
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      
      output.elasticsearch:
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
        protocol: https
        hosts: ["https://elasticsearch-master:9200"]
        ssl.certificate_authorities:
          - /usr/share/filebeat/config/certs/elastic-certificate.pem
```
but the generated configmap always looks like:
ilebeat.inputs:
```
- type: container
  paths:
    - /var/log/containers/*.log
  processors:
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      matchers:
      - logs_path:
          logs_path: "/var/log/containers/"

output.elasticsearch:
  host: '${NODE_NAME}'
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

```
I manually packaged this chart and installed it from the `tgz` file it works perfectly.
