### ISSUE TITLE
Metric Beats and Filebeats collide with hostNetworking enabled.

### ISSUE THREAD

**Issue by kwsorensen** [elastic/helm-charts#995]
**Chart version:** 7.10

**Kubernetes version:** 1.19

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) Docker-Desktop

**Helm Version:** 3

**Describe the bug:**
Using metricbeat and filebeat helm charts with hostNetworking enabled collide on ports.

**Steps to reproduce:**

1. Helm install metricbeats with hostNetworking set to true
2. Helm install filebeat with hostNetworking set to true
3. Filebeat will fail to setup it's HTTP Server on port 5066.

Disabling the hostNetworking feature on either of the helm charts s

**Expected behavior:**
Default values for hostNetworking should not collide. 
We are integrating with elastic cloud and want auto-scaling daemonsets for our kubernetes nodes for metrics and logs.

I suggest the default values for one of the ports should change.

**Provide logs and/or server output (if relevant):**

kubectl logs filebeat-filebeat-qtb4b
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:645    Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs]
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:653    Beat ID: 512fcc30-bdf3-4b6a-a875-8c219a5b402e
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:412    filebeat stopped.
2020-12-21T21:03:23.799Z        ERROR   instance/beat.go:956    Exiting: could not start the HTTP server for the API: listen tcp 127.0.0.1:5066: bind: address already in use
Exiting: could not start the HTTP server for the API: listen tcp 127.0.0.1:5066: bind: address already in use

**Comment by kwsorensen** [comment]
I believed that I have solved this by adding the following the filebeat values file.

filebeatConfig.http.port: "5607"

However in elastic the host.name is set to the name of the pod while kubernetes.host.name is the actual desired name. 

![image](https://user-images.githubusercontent.com/29787085/102824947-0fdbff80-439b-11eb-947f-fe1dd8811dbc.png)

**Comment by kwsorensen** [comment]
Note: I have found a work around which is to modify the filebeatConfig.filebeat.yml to include http.port as 5067.

`filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    http.port: "5067"
hostNetworking: "true"`

**Comment by kwsorensen** [comment]
Note I have found a work around which includes changing the filebeat port. 

```
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    http.port: "5067"
hostNetworking: "true"
```
